// Generated by GitHub Copilot
/**
 * Returns a readable 24-hour time in HH:MM:SS format from an ISO-like input.
 */
export function formatTimeHms(value: string | null | undefined): string {
  if (!value) {
    return "00:00:00";
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "00:00:00";
  }

  const hours = String(parsed.getHours()).padStart(2, "0");
  const minutes = String(parsed.getMinutes()).padStart(2, "0");
  const seconds = String(parsed.getSeconds()).padStart(2, "0");
  return `${hours}:${minutes}:${seconds}`;
}

// Generated by GitHub Copilot
/**
 * Returns a readable local date-time in YYYY-MM-DD HH:MM:SS format.
 */
export function formatDateTimeHms(value: string | null | undefined): string {
  if (!value) {
    return "not set";
  }

  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return `${value} 00:00:00`;
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  const year = parsed.getFullYear();
  const month = String(parsed.getMonth() + 1).padStart(2, "0");
  const day = String(parsed.getDate()).padStart(2, "0");
  return `${year}-${month}-${day} ${formatTimeHms(value)}`;
}