// Generated by GitHub Copilot
/**
 * Returns a 12-hour time in H:MM AM/PM format from an ISO-like input.
 */
export function formatTimeHms(value: string | null | undefined): string {
  if (!value) {
    return "12:00 AM";
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return "12:00 AM";
  }

  const rawHours = parsed.getHours();
  const minutes = String(parsed.getMinutes()).padStart(2, "0");
  const meridiem = rawHours >= 12 ? "PM" : "AM";
  const hours = rawHours % 12 === 0 ? 12 : rawHours % 12;
  return `${hours}:${minutes} ${meridiem}`;
}

// Generated by GitHub Copilot
/**
 * Returns a readable local date-time in YYYY-MM-DD H:MM AM/PM format.
 */
export function formatDateTimeHms(value: string | null | undefined): string {
  if (!value) {
    return "not set";
  }

  if (/^\d{4}-\d{2}-\d{2}$/.test(value)) {
    return value;
  }

  const parsed = new Date(value);
  if (Number.isNaN(parsed.getTime())) {
    return value;
  }

  const year = parsed.getFullYear();
  const month = String(parsed.getMonth() + 1).padStart(2, "0");
  const day = String(parsed.getDate()).padStart(2, "0");
  return `${year}-${month}-${day} ${formatTimeHms(value)}`;
}