import {
  createGoal,
  createHabit,
  deleteGoal,
  listGoals,
  listHabits,
  updateGoal,
} from "@/lib/persistence";
import { Goal, GoalCategory, HabitCategory } from "@/types";

const SYSTEM_WEEKLY_GOAL_TITLES = [
  "Career Learning Sprint",
  "Family Connection Block",
  "Finance Savings Discipline",
  "Peace Recovery Routine",
] as const;

const EXPECTED_MASTER_GOALS: Record<GoalCategory, string> = {
  career: "Become strong in React, System Design, and AI",
  family: "Build peaceful and stable family life",
  finance: "Achieve financial discipline and savings growth",
  peace: "Maintain calm mind and healthy routine",
};

interface HabitTemplate {
  sourceMatchWords: string[];
  title: string;
  category: HabitCategory;
  targetFrequency: number;
  similarWords: string[];
}

const SYSTEM_GOAL_TO_HABIT_TEMPLATES: HabitTemplate[] = [
  {
    sourceMatchWords: ["career", "learning", "sprint"],
    title: "Daily learning (React/AI)",
    category: "learning",
    targetFrequency: 7,
    similarWords: ["daily", "learning", "react", "ai"],
  },
  {
    sourceMatchWords: ["family", "connection", "block"],
    title: "Spend quality time with family",
    category: "family",
    targetFrequency: 7,
    similarWords: ["family", "quality", "time"],
  },
  {
    sourceMatchWords: ["finance", "savings", "discipline"],
    title: "Track expenses / savings awareness",
    category: "other",
    targetFrequency: 7,
    similarWords: ["track", "expenses", "savings"],
  },
  {
    sourceMatchWords: ["peace", "recovery", "routine"],
    title: "5 min silence / mental reset",
    category: "reflection",
    targetFrequency: 7,
    similarWords: ["silence", "mental", "reset"],
  },
];

export interface GoalsCleanupAudit {
  deletedGoalIds: string[];
  deletedGoalTitles: string[];
  updatedGoalIds: string[];
  createdGoalIds: string[];
  createdHabitIds: string[];
  warnings: string[];
  finalMasterGoalsCount: number;
  finalMonthlyGoalsCount: number;
}

/**
 * Normalizes a string to improve duplicate and similarity checks.
 */
function normalize(value: string): string {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9\s]/g, " ")
    .replace(/\s+/g, " ")
    .trim();
}

/**
 * Returns true when every word exists in the source text.
 */
function includesAllWords(source: string, words: string[]): boolean {
  return words.every((word) => source.includes(word));
}

/**
 * Returns the habit template that matches a removed system goal title.
 */
function matchHabitTemplate(goalTitle: string): HabitTemplate | null {
  const source = normalize(goalTitle);
  const template = SYSTEM_GOAL_TO_HABIT_TEMPLATES.find((item) => includesAllWords(source, item.sourceMatchWords));
  return template ?? null;
}

/**
 * Returns true when a similar habit already exists.
 */
function hasSimilarHabit(
  existingHabits: Array<{ title: string; category: HabitCategory }>,
  template: HabitTemplate,
): boolean {
  return existingHabits.some((habit) => {
    if (habit.category !== template.category) {
      return false;
    }

    const normalizedHabitTitle = normalize(habit.title);
    const overlapCount = template.similarWords.filter((word) => normalizedHabitTitle.includes(word)).length;
    return overlapCount >= 2 || normalizedHabitTitle === normalize(template.title);
  });
}

/**
 * Cleans the goals structure and migrates removed weekly system goals to habits.
 * Security: Uses existing RLS-protected persistence calls and never mutates user ownership.
 */
// Generated by GitHub Copilot
export async function cleanupGoalsStructure(userId: string): Promise<GoalsCleanupAudit> {
  const audit: GoalsCleanupAudit = {
    deletedGoalIds: [],
    deletedGoalTitles: [],
    updatedGoalIds: [],
    createdGoalIds: [],
    createdHabitIds: [],
    warnings: [],
    finalMasterGoalsCount: 0,
    finalMonthlyGoalsCount: 0,
  };

  let goals = await listGoals();
  let habits = await listHabits();

  const deleteGoalWithAudit = async (goal: Goal) => {
    await deleteGoal(goal.id);
    audit.deletedGoalIds.push(goal.id);
    audit.deletedGoalTitles.push(goal.title);
    goals = goals.filter((currentGoal) => currentGoal.id !== goal.id);
  };

  const updateGoalWithAudit = async (goal: Goal, payload: Parameters<typeof updateGoal>[1]) => {
    const updatedGoal = await updateGoal(goal.id, payload);
    audit.updatedGoalIds.push(goal.id);
    goals = goals.map((currentGoal) => (currentGoal.id === updatedGoal.id ? updatedGoal : currentGoal));
  };

  // 1) Remove weekly system goals (milestone + weekly).
  const weeklySystemGoals = goals.filter(
    (goal) => (goal.goalType ?? "task") === "milestone" && (goal.period ?? "one-time") === "weekly",
  );

  for (const goal of weeklySystemGoals) {
    await deleteGoalWithAudit(goal);
  }

  // 2) Finance monthly cleanup: remove monthly budget adjustment duplicates.
  const financeMonthlyGoals = goals.filter(
    (goal) => goal.category === "finance" && (goal.period ?? "one-time") === "monthly",
  );

  const budgetAdjustGoals = financeMonthlyGoals.filter((goal) => normalize(goal.title).includes("adjust monthly budget"));
  for (const goal of budgetAdjustGoals) {
    if (goal.completed) {
      audit.warnings.push(`Skipped deleting completed finance goal: \"${goal.title}\" (${goal.id})`);
      continue;
    }
    await deleteGoalWithAudit(goal);
  }

  // 3) Ensure exactly one master goal per pillar with expected canonical title.
  const categories: GoalCategory[] = ["career", "family", "finance", "peace"];

  for (const category of categories) {
    const expectedTitle = EXPECTED_MASTER_GOALS[category];
    const categoryMasterGoals = goals
      .filter((goal) => goal.category === category && (goal.goalType ?? "task") === "master")
      .sort((left, right) => new Date(left.createdAt).getTime() - new Date(right.createdAt).getTime());

    let keeper = categoryMasterGoals.find((goal) => normalize(goal.title) === normalize(expectedTitle));

    if (!keeper && categoryMasterGoals.length > 0) {
      keeper = categoryMasterGoals[0];
      await updateGoalWithAudit(keeper, {
        title: expectedTitle,
        description: keeper.description ?? "",
        category: keeper.category,
        subCategory: keeper.subCategory ?? null,
        targetDate: keeper.targetDate ?? null,
        goalType: "master",
        period: "one-time",
        repeat: "none",
        levelCurrent: keeper.levelCurrent ?? 1,
        levelTarget: keeper.levelTarget ?? 5,
      });
    }

    if (!keeper) {
      const created = await createGoal(userId, {
        title: expectedTitle,
        description: "",
        category,
        subCategory: null,
        targetDate: null,
        goalType: "master",
        period: "one-time",
        repeat: "none",
        levelCurrent: 1,
        levelTarget: 5,
      });
      audit.createdGoalIds.push(created.id);
      goals = [created, ...goals];
      keeper = created;
    }

    const duplicates = categoryMasterGoals.filter((goal) => goal.id !== keeper.id);
    for (const duplicate of duplicates) {
      await deleteGoalWithAudit(duplicate);
    }
  }

  // 4) Move removed weekly system goals to habits (idempotent based on title/category similarity).
  const removedSystemGoalTitles = audit.deletedGoalTitles.filter((title) =>
    SYSTEM_WEEKLY_GOAL_TITLES.some((templateTitle) => normalize(templateTitle) === normalize(title)),
  );

  for (const goalTitle of removedSystemGoalTitles) {
    const template = matchHabitTemplate(goalTitle);
    if (!template) {
      continue;
    }

    if (hasSimilarHabit(habits, template)) {
      continue;
    }

    const createdHabit = await createHabit(userId, {
      title: template.title,
      category: template.category,
      targetFrequency: template.targetFrequency,
    });

    audit.createdHabitIds.push(createdHabit.id);
    habits = [createdHabit, ...habits];
  }

  // 5) Validate final goal structure.
  goals = await listGoals();
  const finalMasterGoals = goals.filter((goal) => (goal.goalType ?? "task") === "master");
  const finalMonthlyGoals = goals.filter((goal) => (goal.period ?? "one-time") === "monthly");
  audit.finalMasterGoalsCount = finalMasterGoals.length;
  audit.finalMonthlyGoalsCount = finalMonthlyGoals.length;

  if (audit.finalMasterGoalsCount !== 4) {
    audit.warnings.push(`Expected exactly 4 master goals, found ${audit.finalMasterGoalsCount}.`);
  }

  if (audit.finalMonthlyGoalsCount > 10) {
    audit.warnings.push(`Monthly goals exceed recommended maximum: ${audit.finalMonthlyGoalsCount}.`);
  }

  if (audit.finalMonthlyGoalsCount < 6) {
    audit.warnings.push(`Monthly goals are below recommended range (6-10): ${audit.finalMonthlyGoalsCount}.`);
  }

  // Audit logs for traceability.
  console.log("[GoalsCleanup] Deleted goal IDs:", audit.deletedGoalIds);
  console.log("[GoalsCleanup] Deleted goal titles:", audit.deletedGoalTitles);
  console.log("[GoalsCleanup] Updated goal IDs:", audit.updatedGoalIds);
  console.log("[GoalsCleanup] Created master goal IDs:", audit.createdGoalIds);
  console.log("[GoalsCleanup] Created habit IDs:", audit.createdHabitIds);
  console.log("[GoalsCleanup] Final counts:", {
    masterGoals: audit.finalMasterGoalsCount,
    monthlyGoals: audit.finalMonthlyGoalsCount,
  });

  if (audit.warnings.length > 0) {
    console.warn("[GoalsCleanup] Warnings:", audit.warnings);
  }

  return audit;
}
