import { Goal } from "@/types";

export interface SuggestedTask {
  goalId: string;
  goalTitle: string;
  title: string;
}

/**
 * Returns true when a goal should behave as a reusable milestone template.
 */
// Generated by GitHub Copilot
export function isRecurringMilestoneGoal(goal: Goal): boolean {
  return (goal.goalType ?? "task") === "milestone" && (goal.repeat === "monthly" || goal.repeat === "weekly");
}

/**
 * Filters goals to recurring milestone templates.
 */
// Generated by GitHub Copilot
export function getRecurringMilestoneGoals(goals: Goal[]): Goal[] {
  return goals.filter(isRecurringMilestoneGoal);
}

/**
 * Returns the UI label for recurring milestone goals.
 */
// Generated by GitHub Copilot
export function getRecurringGoalLabel(goal: Goal): string | null {
  if (!isRecurringMilestoneGoal(goal)) {
    return null;
  }

  if (goal.repeat === "monthly") {
    return "Recurring Monthly Goal";
  }

  if (goal.repeat === "weekly") {
    return "Recurring Weekly Goal";
  }

  return null;
}

/**
 * Builds optional, non-invasive task suggestions from active recurring milestone goals.
 */
// Generated by GitHub Copilot
export function getSuggestedTasks(goals: Goal[]): SuggestedTask[] {
  const recurringGoals = getRecurringMilestoneGoals(goals).filter((goal) => !goal.completed);
  const suggestions: SuggestedTask[] = [];

  recurringGoals.forEach((goal) => {
    const title = goal.title.toLowerCase();

    if (title.includes("health") || title.includes("fit") || title.includes("wellness")) {
      suggestions.push(
        { goalId: goal.id, goalTitle: goal.title, title: "Walk 20 mins" },
        { goalId: goal.id, goalTitle: goal.title, title: "Stretching" },
      );
      return;
    }

    if (title.includes("career") || title.includes("work") || title.includes("learning")) {
      suggestions.push(
        { goalId: goal.id, goalTitle: goal.title, title: "Deep work 60 mins" },
        { goalId: goal.id, goalTitle: goal.title, title: "Skill practice" },
      );
      return;
    }

    if (title.includes("finance") || title.includes("money") || title.includes("saving")) {
      suggestions.push(
        { goalId: goal.id, goalTitle: goal.title, title: "Review expenses" },
        { goalId: goal.id, goalTitle: goal.title, title: "Update savings tracker" },
      );
      return;
    }

    if (title.includes("family") || title.includes("kids") || title.includes("home")) {
      suggestions.push(
        { goalId: goal.id, goalTitle: goal.title, title: "Family check-in" },
        { goalId: goal.id, goalTitle: goal.title, title: "Plan kids activity" },
      );
      return;
    }

    if (title.includes("peace") || title.includes("mind") || title.includes("calm")) {
      suggestions.push(
        { goalId: goal.id, goalTitle: goal.title, title: "Breathing exercise" },
        { goalId: goal.id, goalTitle: goal.title, title: "10-min reflection" },
      );
      return;
    }

    suggestions.push(
      { goalId: goal.id, goalTitle: goal.title, title: `Work on ${goal.title}` },
      { goalId: goal.id, goalTitle: goal.title, title: `Review progress for ${goal.title}` },
    );
  });

  return suggestions;
}
