// Generated by GitHub Copilot
import { DailyTask, Goal, SubCategory, WeeklyReview, WeekTag, LevelUpSuggestion } from "@/types";

/**
 * Returns the level progress percentage for a goal (0-100).
 */
export function getLevelProgress(goal: Goal): number {
  const target = goal.levelTarget ?? 5;
  const current = goal.levelCurrent ?? 1;
  if (!target || target === 0) {
    return 0;
  }
  return Math.min(100, Math.round((current / target) * 100));
}

/**
 * Returns the week-of-month bucket for a given date.
 *
 * @param date - The date to test; defaults to today.
 */
export function getWeekOfMonth(date: Date = new Date()): WeekTag {
  const day = date.getDate();
  if (day <= 7) return "week1";
  if (day <= 14) return "week2";
  if (day <= 21) return "week3";
  return "week4";
}

/**
 * Returns the current week tag based on today.
 */
export function currentWeekTag(): WeekTag {
  return getWeekOfMonth(new Date());
}

/**
 * Returns the first day of the current month as a YYYY-MM-DD string.
 */
export function currentMonthStart(): string {
  const now = new Date();
  return `${now.getFullYear()}-${String(now.getMonth() + 1).padStart(2, "0")}-01`;
}

/**
 * Evaluates whether a goal meets the conditions for a level-up suggestion.
 *
 * Conditions:
 *  1. The last 4 weekly reviews for the matching pillar have an average score >= 4.
 *  2. The goal is not yet at max level.
 *
 * @param goal - The goal to inspect.
 * @param reviews - All weekly reviews, newest first.
 */
export function getLevelUpSuggestion(
  goal: Goal,
  reviews: WeeklyReview[],
): LevelUpSuggestion {
  const levelCurrent = goal.levelCurrent ?? 1;
  const levelTarget = goal.levelTarget ?? 5;
  if (levelCurrent >= levelTarget) {
    return { canLevelUp: false, message: "Already at maximum level." };
  }

  const last4 = reviews.slice(0, 4);
  if (last4.length < 4) {
    return { canLevelUp: false, message: "Need at least 4 weekly reviews to assess." };
  }

  const pillarKey: Record<string, keyof WeeklyReview> = {
    career: "careerScore",
    family: "familyScore",
    finance: "financeScore",
    peace: "peaceScore",
  };

  const reviewKey = pillarKey[goal.category];
  if (!reviewKey) {
    return { canLevelUp: false, message: "Unknown goal category." };
  }

  const avgScore =
    last4.reduce((sum, review) => sum + (review[reviewKey] as number), 0) / 4;

  if (avgScore >= 4) {
    return {
      canLevelUp: true,
      message: `Ready to move to level ${levelCurrent + 1} — average ${goal.category} score over last 4 weeks is ${avgScore.toFixed(1)}/10.`,
    };
  }

  return {
    canLevelUp: false,
    message: `Keep going — average ${goal.category} score is ${avgScore.toFixed(1)}/10 (need ≥ 4.0 over 4 weeks).`,
  };
}

/**
 * Maps a weekly review pillar score to a numeric progress increment (0-100).
 * Score 1-3 = Low → 20 points, 4-6 = Mid → 40 points, 7-10 = High → 60-100 points.
 */
export function pillarScoreToProgress(score: number): number {
  return Math.min(100, Math.round(score * 10));
}

/**
 * Returns the suggested text for a monthly review based on the lowest category.
 */
export function getMonthlyImprovementSuggestion(
  reviews: WeeklyReview[],
): { lowestCategory: string; suggestion: string } {
  if (reviews.length === 0) {
    return { lowestCategory: "—", suggestion: "Complete weekly reviews to get monthly suggestions." };
  }

  const currentMonth = new Date().getMonth();
  const currentYear = new Date().getFullYear();

  const monthlyReviews = reviews.filter((review) => {
    const d = new Date(review.weekStart);
    return d.getMonth() === currentMonth && d.getFullYear() === currentYear;
  });

  const pool = monthlyReviews.length > 0 ? monthlyReviews : reviews.slice(0, 4);

  const avg = (key: keyof WeeklyReview) => {
    const sum = pool.reduce((acc, r) => acc + (r[key] as number), 0);
    return sum / pool.length;
  };

  const categories: Array<{ key: keyof WeeklyReview; label: string }> = [
    { key: "careerScore", label: "Career" },
    { key: "familyScore", label: "Family" },
    { key: "financeScore", label: "Finance" },
    { key: "peaceScore", label: "Peace" },
  ];

  const scores = categories.map((c) => ({ ...c, avg: avg(c.key) }));
  scores.sort((a, b) => a.avg - b.avg);
  const lowest = scores[0];

  const suggestions: Record<string, string> = {
    Career: "Focus on one meaningful project output per week to build career momentum.",
    Family: "Set one dedicated family time block each week—protect it from work.",
    Finance: "Review your spending categories and identify one pattern to reduce.",
    Peace: "Add 10 minutes of silence or reflection to your daily routine.",
  };

  return {
    lowestCategory: lowest.label,
    suggestion: suggestions[lowest.label] ?? "Keep showing up consistently.",
  };
}

/**
 * Generated by GitHub Copilot
 * Maps week_tag to kids focus area theme
 */
export function getWeekFocusArea(weekTag: WeekTag): { week: string; focus: string; description: string } {
  switch (weekTag) {
    case "week1":
      return { week: "Week 1", focus: "Language", description: "Storytelling, naming, talking" };
    case "week2":
      return { week: "Week 2", focus: "Discipline", description: "Clean toys, habits, patience" };
    case "week3":
      return { week: "Week 3", focus: "Physical", description: "Play, running, ball games" };
    case "week4":
      return { week: "Week 4", focus: "Values", description: "Sharing, respect, helping" };
  }
}

/**
 * Generated by GitHub Copilot
 * Determines if a kids task should be shown based on current week
 */
export function shouldShowKidsTask(taskWeekTag: WeekTag | null | undefined): boolean {
  if (!taskWeekTag) {
    return true;
  }
  return taskWeekTag === currentWeekTag();
}

/**
 * Generated by GitHub Copilot
 * Calculates tasks breakdown by sub-category for a given pillar
 */
export interface SubCategoryBreakdown {
  name: SubCategory;
  count: number;
  completed: number;
  percentage: number;
}

/**
 * Generated by GitHub Copilot
 * Gets breakdown stats for family sub-categories (kids, general)
 */
export function getFamilySubCategoryBreakdown(tasks: DailyTask[]): SubCategoryBreakdown[] {
  const familyTasks = tasks.filter((t) => t.category === "family");
  const kids = familyTasks.filter((t) => t.subCategory === "kids" || (!t.subCategory && false));
  const general = familyTasks.filter((t) => t.subCategory === "general" || !t.subCategory);

  const kidsCompleted = kids.filter((t) => t.completed).length;
  const generalCompleted = general.filter((t) => t.completed).length;

  const result: SubCategoryBreakdown[] = [
    {
      name: "kids" as SubCategory,
      count: kids.length,
      completed: kidsCompleted,
      percentage: kids.length ? Math.round((kidsCompleted / kids.length) * 100) : 0,
    },
    {
      name: "general" as SubCategory,
      count: general.length,
      completed: generalCompleted,
      percentage: general.length ? Math.round((generalCompleted / general.length) * 100) : 0,
    },
  ].filter((b) => b.count > 0);
  
  return result;
}

/**
 * Generated by GitHub Copilot
 * Gets breakdown stats for peace sub-categories (health, personal, general)
 */
export function getPeaceSubCategoryBreakdown(tasks: DailyTask[]): SubCategoryBreakdown[] {
  const peaceTasks = tasks.filter((t) => t.category === "peace");
  const health = peaceTasks.filter((t) => t.subCategory === "health");
  const personal = peaceTasks.filter((t) => t.subCategory === "personal");
  const general = peaceTasks.filter((t) => t.subCategory === "general" || !t.subCategory);

  const healthCompleted = health.filter((t) => t.completed).length;
  const personalCompleted = personal.filter((t) => t.completed).length;
  const generalCompleted = general.filter((t) => t.completed).length;

  const result: SubCategoryBreakdown[] = [
    {
      name: "health" as SubCategory,
      count: health.length,
      completed: healthCompleted,
      percentage: health.length ? Math.round((healthCompleted / health.length) * 100) : 0,
    },
    {
      name: "personal" as SubCategory,
      count: personal.length,
      completed: personalCompleted,
      percentage: personal.length ? Math.round((personalCompleted / personal.length) * 100) : 0,
    },
    {
      name: "general" as SubCategory,
      count: general.length,
      completed: generalCompleted,
      percentage: general.length ? Math.round((generalCompleted / general.length) * 100) : 0,
    },
  ].filter((b) => b.count > 0);
  
  return result;
}
