// Generated by GitHub Copilot
import { DailyTask, Goal, WeeklyReview } from "@/types";

const LEVEL_THRESHOLDS: Record<number, number> = {
  1: 0,
  2: 10,
  3: 25,
  4: 50,
  5: 100,
};

export interface GoalLevelSnapshot {
  completedTasks: number;
  recommendedLevel: number;
  nextLevel: number;
  nextLevelThreshold: number | null;
  progressToNextPercent: number;
  canPromote: boolean;
  canSuggestUpgrade: boolean;
  suggestionMessage: string;
}

/**
 * Returns linked completed task count for the provided goal.
 */
export function getCompletedLinkedTasks(goal: Goal, tasks: DailyTask[]): number {
  return tasks.filter((task) => task.goalId === goal.id && task.completed).length;
}

/**
 * Calculates recommended level from linked completed task thresholds.
 */
export function calculateGoalLevel(goal: Goal, tasks: DailyTask[]): number {
  const completedTasks = getCompletedLinkedTasks(goal, tasks);
  const targetLevel = Math.max(1, Math.min(goal.levelTarget ?? 5, 5));

  if (completedTasks >= LEVEL_THRESHOLDS[5]) {
    return Math.min(5, targetLevel);
  }
  if (completedTasks >= LEVEL_THRESHOLDS[4]) {
    return Math.min(4, targetLevel);
  }
  if (completedTasks >= LEVEL_THRESHOLDS[3]) {
    return Math.min(3, targetLevel);
  }
  if (completedTasks >= LEVEL_THRESHOLDS[2]) {
    return Math.min(2, targetLevel);
  }

  return 1;
}

/**
 * Returns threshold required to unlock the next level.
 */
export function getNextLevelThreshold(nextLevel: number): number | null {
  if (nextLevel > 5) {
    return null;
  }
  return LEVEL_THRESHOLDS[nextLevel] ?? null;
}

/**
 * Builds a level progression snapshot used by the Goals page UI.
 */
export function getGoalLevelSnapshot(goal: Goal, tasks: DailyTask[], reviews: WeeklyReview[]): GoalLevelSnapshot {
  const currentLevel = goal.levelCurrent ?? 1;
  const targetLevel = goal.levelTarget ?? 5;
  const completedTasks = getCompletedLinkedTasks(goal, tasks);
  const recommendedLevel = calculateGoalLevel(goal, tasks);
  const nextLevel = Math.min(currentLevel + 1, targetLevel, 5);
  const nextLevelThreshold = currentLevel >= targetLevel ? null : getNextLevelThreshold(nextLevel);

  const previousThreshold = currentLevel <= 1 ? 0 : (getNextLevelThreshold(currentLevel) ?? 0);
  const span = nextLevelThreshold ? Math.max(1, nextLevelThreshold - previousThreshold) : 1;
  const progressBase = Math.max(0, completedTasks - previousThreshold);
  const progressToNextPercent = nextLevelThreshold
    ? Math.min(100, Math.round((progressBase / span) * 100))
    : 100;

  const canPromote = currentLevel < targetLevel && recommendedLevel > currentLevel;

  const last4 = [...reviews]
    .sort((a, b) => b.weekStart.localeCompare(a.weekStart))
    .slice(0, 4);
  const averageLast4 = last4.length === 4
    ? last4.reduce((sum, review) => sum + review.lifeBalanceScore, 0) / 4
    : 0;

  const canSuggestUpgrade = canPromote && last4.length === 4 && averageLast4 > 4;
  const suggestionMessage = canSuggestUpgrade
    ? `Ready to move to Level ${nextLevel}? Last 4 weeks average score is ${averageLast4.toFixed(1)} and task threshold is met.`
    : "";

  return {
    completedTasks,
    recommendedLevel,
    nextLevel,
    nextLevelThreshold,
    progressToNextPercent,
    canPromote,
    canSuggestUpgrade,
    suggestionMessage,
  };
}
