// Generated by GitHub Copilot
import { DailyTask, Goal, HabitLog, Habit, WeeklyReview, LifePillar } from "@/types";

/**
 * Monthly aggregated insights and metrics
 */
export interface MonthlyInsights {
  // Pillar scores and averages
  pillarAverages: Record<LifePillar, number>;
  bestPillar: LifePillar;
  weakestPillar: LifePillar;
  
  // Task metrics
  completedTasks: number;
  totalTasks: number;
  taskCompletionRate: number;
  
  // Habit consistency
  habitCompletionRate: number;
  completedHabits: number;
  totalHabits: number;
  
  // Goals
  completedGoals: number;
  totalGoals: number;
  
  // Summary text
  improved: string;
  notImproved: string;
  levelChange: string;
}

/**
 * Aggregates data for a given month and generates insights.
 *
 * @param month - ISO string for month start (YYYY-MM-01)
 * @param weeklyReviews - All weekly reviews
 * @param dailyTasks - All daily tasks
 * @param goals - All goals
 * @param habits - All habits
 * @param habitLogs - All habit logs
 */
export function generateMonthlyInsights(
  month: string,
  weeklyReviews: WeeklyReview[],
  dailyTasks: DailyTask[],
  goals: Goal[],
  habits: Habit[],
  habitLogs: HabitLog[],
): MonthlyInsights {
  // Get month boundaries
  const monthDate = new Date(`${month}T00:00:00Z`);
  const monthStart = new Date(monthDate.getFullYear(), monthDate.getMonth(), 1);
  const monthEnd = new Date(monthDate.getFullYear(), monthDate.getMonth() + 1, 0, 23, 59, 59);

  // === A. WEEKLY AVERAGES ===
  const weeksInMonth = weeklyReviews.filter((wr) => {
    const weekDate = new Date(`${wr.weekStart}T00:00:00Z`);
    return weekDate >= monthStart && weekDate <= monthEnd;
  });

  const pillarAverages: Record<LifePillar, number> = {
    career: 0,
    family: 0,
    finance: 0,
    peace: 0,
  };

  if (weeksInMonth.length > 0) {
    pillarAverages.career =
      weeksInMonth.reduce((sum, wr) => sum + wr.careerScore, 0) / weeksInMonth.length;
    pillarAverages.family =
      weeksInMonth.reduce((sum, wr) => sum + wr.familyScore, 0) / weeksInMonth.length;
    pillarAverages.finance =
      weeksInMonth.reduce((sum, wr) => sum + wr.financeScore, 0) / weeksInMonth.length;
    pillarAverages.peace =
      weeksInMonth.reduce((sum, wr) => sum + wr.peaceScore, 0) / weeksInMonth.length;
  }

  // === B. TASK COMPLETION ===
  const monthTasks = dailyTasks.filter((task) => {
    const taskDate = new Date(`${task.createdAt.slice(0, 10)}T00:00:00Z`);
    return taskDate >= monthStart && taskDate <= monthEnd;
  });

  const completedTasks = monthTasks.filter((t) => t.completed).length;
  const totalTasks = monthTasks.length;
  const taskCompletionRate = totalTasks > 0 ? (completedTasks / totalTasks) * 100 : 0;

  // === C. HABIT CONSISTENCY ===
  // Assume habits exist for the month; count completed logs
  const monthHabitLogs = habitLogs.filter((log) => {
    const logDate = new Date(`${log.completedDate}T00:00:00Z`);
    return logDate >= monthStart && logDate <= monthEnd;
  });

  // Expected habit completions: habits.length * days in month
  const daysInMonth = Math.ceil(
    (monthEnd.getTime() - monthStart.getTime()) / (1000 * 60 * 60 * 24)
  );
  const totalHabits = habits.length;
  const totalExpectedHabitLogs = totalHabits * daysInMonth;
  const completedHabits = monthHabitLogs.length;
  const habitCompletionRate =
    totalExpectedHabitLogs > 0 ? (completedHabits / totalExpectedHabitLogs) * 100 : 0;

  // === D. GOALS ===
  const monthGoals = goals.filter((goal) => {
    const goalDate = new Date(`${goal.createdAt.slice(0, 10)}T00:00:00Z`);
    return goalDate >= monthStart && goalDate <= monthEnd;
  });

  const completedGoals = monthGoals.filter((g) => g.completed).length;
  const totalGoals = monthGoals.length;

  // === E. PILLAR BEST/WORST ===
  const pillars: Array<[LifePillar, number]> = [
    ["career", pillarAverages.career],
    ["family", pillarAverages.family],
    ["finance", pillarAverages.finance],
    ["peace", pillarAverages.peace],
  ];

  const bestPillar = pillars.reduce((a, b) => (a[1] > b[1] ? a : b))[0];
  const weakestPillar = pillars.reduce((a, b) => (a[1] < b[1] ? a : b))[0];

  // === F. GENERATE TEXT INSIGHTS ===
  const improvedReasons: string[] = [];
  const notImprovedReasons: string[] = [];

  // Improved: check for high scores and completion rates
  for (const [pillar, score] of pillars) {
    if (score >= 4) improvedReasons.push(pillar);
  }

  if (taskCompletionRate > 70) {
    improvedReasons.push("strong task completion");
  }

  if (completedGoals > 0) {
    improvedReasons.push(`${completedGoals} goal${completedGoals > 1 ? "s" : ""} completed`);
  }

  // Not improved: check for low scores and low completion rates
  for (const [pillar, score] of pillars) {
    if (score < 3) notImprovedReasons.push(pillar);
  }

  if (taskCompletionRate < 50) {
    notImprovedReasons.push("low task completion rate");
  }

  if (habitCompletionRate < 50) {
    notImprovedReasons.push("inconsistent habit tracking");
  }

  // Build improved text
  let improvedText = "";
  if (improvedReasons.length > 0) {
    const improvedList = improvedReasons.join(", ");
    improvedText = `Improvements in: ${improvedList}. Consistency building momentum across focused areas.`;
  } else {
    improvedText = "Some progress made. Continue focusing on key areas of development.";
  }

  // Build not improved text
  let notImprovedText = "";
  if (notImprovedReasons.length > 0) {
    const notImprovedList = notImprovedReasons.join(", ");
    notImprovedText = `Areas needing focus: ${notImprovedList}. Prioritize building consistency in these pillars.`;
  } else {
    notImprovedText = "Most areas showing stability. Focus on growth in secondary areas.";
  }

  // Build level change note
  const allScoresHigh = Object.values(pillarAverages).every((s) => s >= 4);
  const levelChangeNote = allScoresHigh
    ? "All pillars performing well. Ready to move to next level."
    : "Continue building consistency before advancing to the next level.";

  return {
    pillarAverages,
    bestPillar,
    weakestPillar,
    completedTasks,
    totalTasks,
    taskCompletionRate: Math.round(taskCompletionRate),
    habitCompletionRate: Math.round(habitCompletionRate),
    completedHabits,
    totalHabits,
    completedGoals,
    totalGoals,
    improved: improvedText,
    notImproved: notImprovedText,
    levelChange: levelChangeNote,
  };
}

/**
 * Fetches AI-refined insights from the monthly-coach API.
 * Falls back to raw insights if API is unavailable.
 */
export async function fetchAIRefinedInsights(insights: MonthlyInsights): Promise<{
  improved: string;
  notImproved: string;
  levelChange: string;
  error: string | null;
}> {
  try {
    const response = await fetch("/api/monthly-coach", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        improved: insights.improved,
        notImproved: insights.notImproved,
        levelChange: insights.levelChange,
        pillarAverages: insights.pillarAverages,
        bestPillar: insights.bestPillar,
        weakestPillar: insights.weakestPillar,
        taskCompletionRate: insights.taskCompletionRate,
        habitCompletionRate: insights.habitCompletionRate,
      }),
      signal: AbortSignal.timeout(10000),
    });

    if (!response.ok) {
      throw new Error(`API returned status ${response.status}`);
    }

    const data = await response.json();
    return {
      improved: data.improved || insights.improved,
      notImproved: data.notImproved || insights.notImproved,
      levelChange: data.levelChange || insights.levelChange,
      error: null,
    };
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : "Failed to fetch refined insights";
    console.warn("AI refinement unavailable, using raw insights:", errorMsg);
    return {
      improved: insights.improved,
      notImproved: insights.notImproved,
      levelChange: insights.levelChange,
      error: null, // Don't show error to user if we have fallback
    };
  }
}
