// Generated by GitHub Copilot
import { useEffect, useState } from "react";
import { DailyTask } from "@/types";
import { STORAGE_KEYS } from "@/constants/storage";

export interface TaskSummary {
  completed: string[];
  pending: string[];
  completionRate: number;
  totalTasks: number;
}

export interface GeneratedNotes {
  summary: string;
  suggestion: string;
  isLoading: boolean;
  error: string | null;
}

export interface WeeklySuggestionHistoryItem {
  id: string;
  userId: string;
  weekStart: string;
  suggestion: string;
  notesText: string;
  completionRate: number;
  lifeBalanceScore: number;
  createdAt: string;
}

/**
 * Generates a formatted summary of completed and pending tasks for the week.
 * Limits to 5 tasks each to keep output concise.
 */
export function generateTaskSummary(tasks: DailyTask[]): TaskSummary {
  const completed = tasks
    .filter((t) => t.completed)
    .map((t) => t.title)
    .slice(0, 5);

  const pending = tasks
    .filter((t) => !t.completed)
    .map((t) => t.title)
    .slice(0, 5);

  const completionRate = tasks.length > 0 ? Math.round((completed.length / tasks.length) * 100) : 0;

  return {
    completed,
    pending,
    completionRate,
    totalTasks: tasks.length,
  };
}

/**
 * Formats task summary into human-readable text for the notes field.
 */
export function formatSummaryAsText(summary: TaskSummary, suggestion?: string): string {
  let text = "";

  if (summary.completed.length > 0) {
    text += "✅ Completed:\n";
    summary.completed.forEach((task) => {
      text += `• ${task}\n`;
    });
    text += "\n";
  }

  if (summary.pending.length > 0) {
    text += "⚠️ Pending:\n";
    summary.pending.forEach((task) => {
      text += `• ${task}\n`;
    });
    text += "\n";
  }

  if (suggestion) {
    text += `💡 AI Suggestion:\n${suggestion}\n`;
  }

  return text.trim();
}

/**
 * Fetches AI-generated improvement suggestions from the server.
 * Returns a fallback message if the API fails.
 */
export async function fetchAISuggestion(
  summary: TaskSummary,
  scores: {
    career: number;
    family: number;
    finance: number;
    peace: number;
  },
): Promise<{ suggestion: string; error: string | null }> {
  try {
    const response = await fetch("/api/weekly-coach", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({
        completedTasks: summary.completed,
        pendingTasks: summary.pending,
        scores,
        completionRate: summary.completionRate,
      }),
    });

    if (!response.ok) {
      console.warn("AI suggestion API failed:", response.statusText);
      return {
        suggestion:
          "Focus on completing pending tasks next week. Identify one key blocker and prioritize removing it.",
        error: null,
      };
    }

    const data = await response.json();
    return {
      suggestion: data.suggestion || "",
      error: null,
    };
  } catch (error) {
    console.error("Error fetching AI suggestion:", error);
    return {
      suggestion:
        "Build momentum by completing high-impact tasks first. Review priorities and adjust as needed.",
      error: error instanceof Error ? error.message : "Unknown error",
    };
  }
}

/**
 * Reads AI suggestion history from local storage.
 */
export function getWeeklySuggestionHistory(userId: string): WeeklySuggestionHistoryItem[] {
  if (typeof window === "undefined") {
    return [];
  }

  try {
    const parsed = JSON.parse(
      localStorage.getItem(STORAGE_KEYS.weeklyAiSuggestionHistory) ?? "[]",
    ) as WeeklySuggestionHistoryItem[];

    return parsed
      .filter((item) => item.userId === userId)
      .sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());
  } catch {
    return [];
  }
}

/**
 * Saves AI suggestion history in local storage (most recent first, capped list).
 */
export function saveWeeklySuggestionHistory(
  item: {
    userId: string;
    weekStart: string;
    suggestion?: string;
    notesText?: string;
    completionRate?: number;
    lifeBalanceScore?: number;
  },
): void {
  if (typeof window === "undefined") {
    return;
  }

  try {
    const parsed = JSON.parse(
      localStorage.getItem(STORAGE_KEYS.weeklyAiSuggestionHistory) ?? "[]",
    ) as WeeklySuggestionHistoryItem[];

    const existingItem = parsed.find(
      (historyItem) => historyItem.userId === item.userId && historyItem.weekStart === item.weekStart,
    );
    const remaining = parsed.filter(
      (historyItem) => !(historyItem.userId === item.userId && historyItem.weekStart === item.weekStart),
    );

    const merged: WeeklySuggestionHistoryItem = {
      id: existingItem?.id ?? crypto.randomUUID(),
      userId: item.userId,
      weekStart: item.weekStart,
      suggestion: item.suggestion ?? existingItem?.suggestion ?? "",
      notesText: item.notesText ?? existingItem?.notesText ?? "",
      completionRate: item.completionRate ?? existingItem?.completionRate ?? 0,
      lifeBalanceScore: item.lifeBalanceScore ?? existingItem?.lifeBalanceScore ?? 0,
      createdAt: existingItem?.createdAt ?? new Date().toISOString(),
    };

    const next: WeeklySuggestionHistoryItem[] = [
      merged,
      ...remaining,
    ].slice(0, 50);

    localStorage.setItem(STORAGE_KEYS.weeklyAiSuggestionHistory, JSON.stringify(next));
  } catch {
    // Ignore storage errors and keep the app functional.
  }
}

/**
 * Cleans up old localStorage history entries by removing duplicates and invalid entries.
 * Called once on app initialization to migrate legacy data patterns.
 */
export function cleanupWeeklySuggestionHistory(): void {
  if (typeof window === "undefined") {
    return;
  }

  try {
    const parsed = JSON.parse(
      localStorage.getItem(STORAGE_KEYS.weeklyAiSuggestionHistory) ?? "[]",
    ) as WeeklySuggestionHistoryItem[];

    if (parsed.length === 0) {
      return;
    }

    // Deduplicate: for each userId+weekStart combo, keep only the most recent entry
    const seen = new Set<string>();
    const deduped: WeeklySuggestionHistoryItem[] = [];

    // Sort by createdAt descending to process newest first
    const sorted = [...parsed].sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );

    for (const item of sorted) {
      const key = `${item.userId}|${item.weekStart}`;
      
      // Skip if already seen or if both content fields are empty
      if (seen.has(key) || (!item.notesText?.trim() && !item.suggestion?.trim())) {
        continue;
      }

      seen.add(key);
      deduped.push(item);
    }

    // Cap at 50 entries and re-sort by createdAt descending
    const cleaned = deduped.slice(0, 50).sort(
      (a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime(),
    );

    if (cleaned.length < parsed.length) {
      localStorage.setItem(STORAGE_KEYS.weeklyAiSuggestionHistory, JSON.stringify(cleaned));
    }
  } catch {
    // Ignore storage errors and keep the app functional.
  }
}
