-- Generated by GitHub Copilot
-- Remediates Supabase lint errors:
-- 0007_policy_exists_rls_disabled
-- 0013_rls_disabled_in_public
-- Safe to run multiple times.

begin;

-- Ensure RLS is enabled on all affected public tables.
alter table public.users enable row level security;
alter table public.weekly_reviews enable row level security;
alter table public.kids_activities enable row level security;
alter table public.finance_entries enable row level security;
alter table public.reflections enable row level security;
alter table public.garden_tasks enable row level security;
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;
alter table public.daily_tasks enable row level security;
alter table public.goals enable row level security;
alter table public.milestones enable row level security;
alter table public.monthly_reviews enable row level security;

-- Remove stale/legacy policy name from lint report for daily_tasks.
drop policy if exists "Users can access their own data" on public.daily_tasks;

-- Canonical owner-scoped policies.
drop policy if exists "Users can access their own profile" on public.users;
create policy "Users can access their own profile"
on public.users
for all
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "Users can access their own daily tasks" on public.daily_tasks;
create policy "Users can access their own daily tasks"
on public.daily_tasks
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own weekly reviews" on public.weekly_reviews;
create policy "Users can access their own weekly reviews"
on public.weekly_reviews
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own goals" on public.goals;
create policy "Users can access their own goals"
on public.goals
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own kids activities" on public.kids_activities;
create policy "Users can access their own kids activities"
on public.kids_activities
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own finance entries" on public.finance_entries;
create policy "Users can access their own finance entries"
on public.finance_entries
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own reflections" on public.reflections;
create policy "Users can access their own reflections"
on public.reflections
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own garden tasks" on public.garden_tasks;
create policy "Users can access their own garden tasks"
on public.garden_tasks
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access their own habits" on public.habits;
create policy "Users can access their own habits"
on public.habits
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "Users can access logs for their habits" on public.habit_logs;
create policy "Users can access logs for their habits"
on public.habit_logs
for all
using (
  exists (
    select 1
    from public.habits
    where public.habits.id = public.habit_logs.habit_id
      and public.habits.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.habits
    where public.habits.id = public.habit_logs.habit_id
      and public.habits.user_id = auth.uid()
  )
);

drop policy if exists "Users can access milestones for their own goals" on public.milestones;
create policy "Users can access milestones for their own goals"
on public.milestones
for all
using (
  exists (
    select 1
    from public.goals
    where public.goals.id = public.milestones.goal_id
      and public.goals.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.goals
    where public.goals.id = public.milestones.goal_id
      and public.goals.user_id = auth.uid()
  )
);

drop policy if exists "Users can access their own monthly reviews" on public.monthly_reviews;
create policy "Users can access their own monthly reviews"
on public.monthly_reviews
for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

commit;
