// Generated by GitHub Copilot
import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

const MONTHLY_COACH_MODELS = [
  "gemini-3-flash-preview",
  "gemini-2.5-flash",
  "gemini-1.5-flash",
];

/**
 * Tries configured Gemini models in priority order until one succeeds.
 */
// Generated by GitHub Copilot
async function generateMonthlyInsights(
  ai: GoogleGenAI,
  prompt: string,
): Promise<string | null> {
  for (const model of MONTHLY_COACH_MODELS) {
    try {
      const response = await ai.models.generateContent({
        model,
        contents: prompt,
        config: {
          temperature: 0.7,
          topP: 0.8,
          maxOutputTokens: 300,
        },
      });

      const text = response.text?.trim();
      if (text) {
        return text;
      }
    } catch (modelError) {
      const message =
        modelError instanceof Error ? modelError.message : String(modelError);
      const isNotFound =
        message.includes("NOT_FOUND") ||
        message.includes("not found") ||
        message.includes("404");

      if (!isNotFound) {
        throw modelError;
      }
    }
  }

  return null;
}

/**
 * POST /api/monthly-coach
 *
 * Refines raw monthly insights using Google Gemini API for a more polished summary.
 * Falls back gracefully if API is unavailable.
 *
 * Request body:
 * {
 *   improved: string,
 *   notImproved: string,
 *   levelChange: string,
 *   pillarAverages: { career, family, finance, peace },
 *   bestPillar: string,
 *   weakestPillar: string,
 *   taskCompletionRate: number,
 *   habitCompletionRate: number
 * }
 */
export async function POST(request: NextRequest) {
  try {
    const payload = await request.json();
    const {
      improved,
      notImproved,
      levelChange,
      pillarAverages,
      bestPillar,
      weakestPillar,
      taskCompletionRate,
      habitCompletionRate,
    } = payload;

    // Validate input
    if (!improved || !notImproved || !levelChange) {
      return NextResponse.json(
        { error: "Missing required insight fields" },
        { status: 400 }
      );
    }

    // Get API key
    const apiKey = process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      console.warn("GEMINI_API_KEY not configured, returning raw insights");
      return NextResponse.json({
        improved,
        notImproved,
        levelChange,
      });
    }

    // Build context-rich prompt
    const prompt = `You are a supportive life coach reviewing someone's monthly progress across 4 life pillars: Career, Family, Finance, and Peace.

Monthly Data:
- Best performing area: ${bestPillar} (avg score: ${pillarAverages[bestPillar as keyof typeof pillarAverages]?.toFixed(1) || "N/A"}/5)
- Area needing focus: ${weakestPillar} (avg score: ${pillarAverages[weakestPillar as keyof typeof pillarAverages]?.toFixed(1) || "N/A"}/5)
- Task completion rate: ${taskCompletionRate}%
- Habit consistency: ${habitCompletionRate}%

Raw insights:
- What improved: ${improved}
- What didn't improve: ${notImproved}
- Level change note: ${levelChange}

Refine these into clear, short, and motivating summaries (keep each under 2 sentences). Focus on:
1. What improved - celebrate the wins, be specific
2. What didn't improve - identify one key area to focus on next
3. Level change - give clear guidance on readiness for growth

Format your response as JSON:
{
  "improved": "...",
  "notImproved": "...",
  "levelChange": "..."
}`;

    const ai = new GoogleGenAI({ apiKey });
    const textContent = await generateMonthlyInsights(ai, prompt);
    if (!textContent) {
      console.warn("No text content in Gemini response");
      return NextResponse.json({
        improved,
        notImproved,
        levelChange,
      });
    }

    // Parse JSON from response
    try {
      const jsonMatch = textContent.match(/\{[\s\S]*\}/);
      if (!jsonMatch) {
        throw new Error("No JSON found in response");
      }

      const refined = JSON.parse(jsonMatch[0]);
      return NextResponse.json({
        improved: refined.improved || improved,
        notImproved: refined.notImproved || notImproved,
        levelChange: refined.levelChange || levelChange,
      });
    } catch (parseErr) {
      console.warn("Failed to parse Gemini response as JSON, using raw insights");
      return NextResponse.json({
        improved,
        notImproved,
        levelChange,
      });
    }
  } catch (error) {
    const errorMsg = error instanceof Error ? error.message : String(error);
    console.error("Monthly coach API error:", errorMsg);

    // Graceful fallback - return raw insights from request if available
    try {
      const payload = await request.json();
      return NextResponse.json({
        improved: payload.improved,
        notImproved: payload.notImproved,
        levelChange: payload.levelChange,
      });
    } catch {
      return NextResponse.json(
        { error: "Failed to process monthly coach request" },
        { status: 500 }
      );
    }
  }
}
