"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  Collapse,
  Divider,
  Grid,
  IconButton,
  MenuItem,
  Stack,
  Switch,
  TextField,
  Typography,
} from "@mui/material";
import ExpandLessRoundedIcon from "@mui/icons-material/ExpandLessRounded";
import ExpandMoreRoundedIcon from "@mui/icons-material/ExpandMoreRounded";
import {
  Bar,
  BarChart,
  CartesianGrid,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import DailyChecklist from "@/components/dashboard/DailyChecklist";
import PageHeader from "@/components/common/PageHeader";
import { useAuth } from "@/lib/auth-context";
import {
  createGoal,
  createDailyTask,
  deleteDailyTask,
  listHabits,
  toggleHabitCompletion,
  updateDailyTask,
  updateDailyTaskCompletion,
  updateDailyTaskGoalLink,
} from "@/lib/persistence";
import {
  currentWeekTag,
  getWeekFocusArea,
  getWeekOfMonth,
  shouldShowKidsTask,
} from "@/lib/goal-utils";
import { addTask, removeTask, replaceTask } from "@/store/slices/dailySlice";
import { addGoal } from "@/store/slices/goalsSlice";
import { setHabits } from "@/store/slices/habitSlice";
import { AppDispatch, RootState } from "@/store/store";
import {
  DailyTask,
  DailyTaskCategory,
  Goal,
  Reflection,
  WeekTag,
} from "@/types";
import { DAILY_DEFAULT_RECURRING_TASKS } from "@/constants/options";
import { STORAGE_KEYS } from "@/constants/storage";

const defaultRecurringTasks: Array<{
  title: string;
  category: DailyTaskCategory;
}> = DAILY_DEFAULT_RECURRING_TASKS;

interface RecurringTemplate {
  title: string;
  category: DailyTaskCategory;
}

interface SuggestedTaskGroup {
  goalTitle: string;
  goalId?: string;
  suggestions: string[];
}

interface SuggestedTaskItem {
  goalId: string;
  goalTitle: string;
  title: string;
  category: DailyTaskCategory;
}

/**
 * Builds small actionable daily suggestions from an active monthly goal title.
 */
// Generated by GitHub Copilot
function buildMonthlyGoalTaskSuggestions(goal: Goal): string[] {
  const normalized = goal.title.toLowerCase();

  if (normalized.includes("react") || normalized.includes("topic")) {
    return ["Watch 1 React video", "Practice 1 concept"];
  }

  if (normalized.includes("budget") || normalized.includes("expense")) {
    return ["Review today expenses for 10 mins", "Update one budget category"];
  }

  if (normalized.includes("sip") || normalized.includes("investment")) {
    return ["Check SIP performance summary", "Read one investment note"];
  }

  if (normalized.includes("saving")) {
    return ["Log today's savings amount", "Compare this week vs last week savings"];
  }

  if (normalized.includes("family") || normalized.includes("kids")) {
    return ["Plan one family activity", "Do one quality family check-in"];
  }

  if (normalized.includes("reflection") || normalized.includes("calm") || normalized.includes("peace")) {
    return ["Do a 10-minute reflection", "Practice 5-minute breathing reset"];
  }

  return [
    `Work 20 mins on ${goal.title}`,
    `Take one small step for ${goal.title}`,
  ];
}

/**
 * Builds a deterministic session cache key for AI suggestions.
 */
// Generated by GitHub Copilot
function buildSuggestionsCacheKey(
  goals: Goal[],
  difficultyHint: "easier" | "balanced" | "advanced",
): string {
  const signature = goals
    .map(
      (goal) =>
        `${goal.id}:${goal.title}:${goal.category}:${goal.subCategory ?? "none"}`,
    )
    .sort()
    .join("|");
  return `${STORAGE_KEYS.taskSuggestionsSession}:${difficultyHint}:${signature}`;
}

function dateOnly(value: string) {
  return value.slice(0, 10);
}

function isTodayTask(task: DailyTask): boolean {
  const today = new Date().toISOString().slice(0, 10);
  const taskDate = task.taskDate ?? dateOnly(task.createdAt);
  return taskDate === today;
}

/**
 * Renders the dedicated daily planner with category visibility for the whole task list.
 */
export default function DailyPlannerPage() {
  const dispatch = useDispatch<AppDispatch>();
  const { user, isHydrating } = useAuth();
  const [error, setError] = useState<string | null>(null);
  const tasks = useSelector((state: RootState) => state.daily.tasks);
  const habits = useSelector((state: RootState) => state.habits.habits);
  const goals = useSelector((state: RootState) => state.goals.goals);
  const reflections = useSelector(
    (state: RootState) => state.reflections.reflections,
  );
  const [quickMode, setQuickMode] = useState(true);
  const [plannerView, setPlannerView] = useState<"today" | "all">("today");
  const [taskSortBy, setTaskSortBy] = useState<
    "category-asc" | "category-desc"
  >("category-asc");
  const [selectedGoalId, setSelectedGoalId] = useState<string | null>(null);
  const [suggestedTasks, setSuggestedTasks] = useState<SuggestedTaskItem[]>([]);
  const [suggestionsLoading, setSuggestionsLoading] = useState(false);
  const [suggestionsError, setSuggestionsError] = useState<string | null>(null);
  const [suggestionPrefill, setSuggestionPrefill] = useState<{
    title: string;
    category: DailyTaskCategory;
    goalId?: string | null;
  } | null>(null);
  const weekTag = currentWeekTag();
  const weekNumber = getWeekOfMonth();
  const [recurringTemplates, setRecurringTemplates] = useState<
    RecurringTemplate[]
  >(defaultRecurringTasks);
  const [repeatExpanded, setRepeatExpanded] = useState(false);
  const [suggestedTasksExpanded, setSuggestedTasksExpanded] = useState(false);
  const [reminderDismissed, setReminderDismissed] = useState(false);
  const initializedRecurringRef = useRef(false);
  const today = new Date().toISOString().slice(0, 10);
  const weekFocus = getWeekFocusArea(weekTag);

  const visibleTasks = useMemo(
    () =>
      tasks.filter(
        (task) =>
          task.subCategory !== "kids" || shouldShowKidsTask(task.weekTag),
      ),
    [tasks],
  );

  const counts = visibleTasks.reduce<Record<string, number>>(
    (summary, task) => {
      summary[task.category] = (summary[task.category] ?? 0) + 1;
      return summary;
    },
    {},
  );

  const todaysTasks = useMemo(
    () => visibleTasks.filter((task) => isTodayTask(task)),
    [visibleTasks],
  );

  const plannerTasks = useMemo(
    () => (plannerView === "today" ? todaysTasks : visibleTasks),
    [plannerView, todaysTasks, visibleTasks],
  );

  const activeMilestoneGoals = useMemo(
    () =>
      goals.filter(
        (goal) =>
          (goal.goalType ?? "task") === "milestone" &&
          (goal.repeat ?? "none") !== "none",
      ),
    [goals],
  );

  // Generated by GitHub Copilot
  const activeMonthlyGoals = useMemo(
    () =>
      goals.filter(
        (goal) =>
          !goal.completed
          && (
            (goal.period ?? "one-time") === "monthly"
            || (goal.repeat ?? "none") === "monthly"
          ),
      ),
    [goals],
  );

  // Generated by GitHub Copilot
  const monthlyGoalSuggestedTasks = useMemo(() => {
    const suggested: SuggestedTaskItem[] = [];

    activeMonthlyGoals.forEach((goal) => {
      const smallTasks = buildMonthlyGoalTaskSuggestions(goal).slice(0, 2);
      smallTasks.forEach((taskTitle) => {
        suggested.push({
          goalId: goal.id,
          goalTitle: goal.title,
          title: taskTitle,
          category: goal.category,
        });
      });
    });

    return suggested;
  }, [activeMonthlyGoals]);

  // Generated by GitHub Copilot
  const mergedSuggestedTasks = useMemo(() => {
    const seen = new Set<string>();
    const merged: SuggestedTaskItem[] = [];

    [...monthlyGoalSuggestedTasks, ...suggestedTasks].forEach((item) => {
      const key = `${item.goalId}:${item.title.toLowerCase()}`;
      if (seen.has(key)) {
        return;
      }
      seen.add(key);
      merged.push(item);
    });

    return merged;
  }, [monthlyGoalSuggestedTasks, suggestedTasks]);

  const recentTaskTitles = useMemo(
    () =>
      [...visibleTasks]
        .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
        .slice(0, 10)
        .map((task) => task.title),
    [visibleTasks],
  );

  const difficultyHint = useMemo<"easier" | "balanced" | "advanced">(() => {
    const latestReflections = [...reflections]
      .sort((a, b) => b.createdAt.localeCompare(a.createdAt))
      .slice(0, 5);

    if (latestReflections.length === 0) {
      return "balanced";
    }

    const averageMood =
      latestReflections.reduce(
        (sum: number, reflection: Reflection) => sum + reflection.mood,
        0,
      ) / latestReflections.length;
    if (averageMood < 5) {
      return "easier";
    }
    if (averageMood >= 8) {
      return "advanced";
    }
    return "balanced";
  }, [reflections]);

  const suggestionsCacheKey = useMemo(
    () => buildSuggestionsCacheKey(activeMilestoneGoals, difficultyHint),
    [activeMilestoneGoals, difficultyHint],
  );

  const filteredPlannerTasks = useMemo(
    () =>
      selectedGoalId
        ? plannerTasks.filter((task) => task.goalId === selectedGoalId)
        : plannerTasks,
    [plannerTasks, selectedGoalId],
  );

  const completionRate = todaysTasks.length
    ? Math.round(
        (todaysTasks.filter((task) => task.completed).length /
          todaysTasks.length) *
          100,
      )
    : 0;

  // Generated by GitHub Copilot - Sort today's tasks by category
  const sortedTodaysTasks = useMemo(() => {
    const sorted = [...filteredPlannerTasks].sort((a, b) => {
      const comparison = a.category.localeCompare(b.category);
      return taskSortBy === "category-asc" ? comparison : -comparison;
    });
    return sorted;
  }, [filteredPlannerTasks, taskSortBy]);

  const trendData = useMemo(() => {
    const grouped = new Map<string, { total: number; done: number }>();
    visibleTasks.forEach((task) => {
      const day = task.taskDate ?? dateOnly(task.createdAt);
      const current = grouped.get(day) ?? { total: 0, done: 0 };
      current.total += 1;
      if (task.completed) {
        current.done += 1;
      }
      grouped.set(day, current);
    });

    return Array.from(grouped.entries())
      .sort((a, b) => a[0].localeCompare(b[0]))
      .slice(-7)
      .map(([day, value]) => ({
        day,
        completionRate: value.total
          ? Math.round((value.done / value.total) * 100)
          : 0,
      }));
  }, [visibleTasks]);

  const repeatConfigTasks = useMemo(() => {
    const byTitle = new Map<
      string,
      { title: string; category: DailyTaskCategory }
    >();
    visibleTasks.forEach((task) => {
      const normalized = task.title.trim().toLowerCase();
      if (!normalized || byTitle.has(normalized)) {
        return;
      }
      byTitle.set(normalized, {
        title: task.title.trim(),
        category: task.category,
      });
    });
    return Array.from(byTitle.values());
  }, [visibleTasks]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    const raw = window.localStorage.getItem(STORAGE_KEYS.recurringTemplates);
    if (!raw) {
      return;
    }
    try {
      const parsed = JSON.parse(raw) as RecurringTemplate[];
      if (Array.isArray(parsed) && parsed.length > 0) {
        setRecurringTemplates(parsed);
      }
    } catch {
      // Keep defaults when local storage is malformed.
    }
  }, []);

  useEffect(() => {
    if (!user || isHydrating || initializedRecurringRef.current) {
      return;
    }

    initializedRecurringRef.current = true;
    const userId = user.id;

    async function ensureDailyAutomation() {
      const todaySet = new Set(
        tasks
          .filter((task) => isTodayTask(task))
          .map((task) => task.title.trim().toLowerCase()),
      );

      const allTemplates = [
        ...defaultRecurringTasks,
        ...recurringTemplates,
      ].filter(
        (template, index, array) =>
          array.findIndex(
            (item) =>
              item.title.trim().toLowerCase() ===
              template.title.trim().toLowerCase(),
          ) === index,
      );

      for (const template of allTemplates) {
        if (todaySet.has(template.title.trim().toLowerCase())) {
          continue;
        }
        const created = await createDailyTask(userId, {
          title: template.title,
          category: template.category,
          taskDate: today,
        });
        dispatch(addTask(created));
      }
    }

    void ensureDailyAutomation().catch((automationError) => {
      setError(
        automationError instanceof Error
          ? automationError.message
          : "Failed to apply daily automation.",
      );
    });
  }, [dispatch, isHydrating, recurringTemplates, tasks, today, user]);

  useEffect(() => {
    if (typeof window === "undefined") {
      return;
    }
    window.localStorage.setItem(
      STORAGE_KEYS.recurringTemplates,
      JSON.stringify(recurringTemplates),
    );
  }, [recurringTemplates]);

  /**
   * Creates a persisted daily task.
   */
  async function handleAddTask(
    title: string,
    category: DailyTaskCategory,
    options?: {
      recurring?: boolean;
      goalId?: string | null;
      subCategory?: string | null;
      weekTag?: WeekTag | null;
      taskDate?: string | null;
    },
  ) {
    if (!user) {
      return;
    }

    try {
      setError(null);
      const isKidsTask =
        category === "family" && options?.subCategory === "kids";
      const resolvedWeekTag = isKidsTask
        ? (options?.weekTag ?? getWeekOfMonth(new Date()))
        : null;
      const task = await createDailyTask(user.id, {
        title,
        category,
        subCategory: options?.subCategory ?? null,
        weekTag: resolvedWeekTag,
        taskDate: options?.taskDate ?? today,
      });
      // Optimistically add to Redux immediately so the list updates without delay.
      dispatch(addTask(task));

      // Best-effort: link to the selected goal. If this fails (e.g. migration not applied),
      // the task is still visible — only the goal link is skipped.
      if (options?.goalId) {
        try {
          const linked = await updateDailyTaskGoalLink(task.id, {
            goalId: options.goalId,
            weekTag: resolvedWeekTag,
          });
          dispatch(replaceTask(linked));
        } catch {
          // Goal-link columns may not exist yet — silently skip; task is already in list.
        }
      }

      if (options?.recurring) {
        setRecurringTemplates((current) => {
          const exists = current.some(
            (template) =>
              template.title.trim().toLowerCase() ===
              title.trim().toLowerCase(),
          );
          if (exists) {
            return current;
          }
          return [...current, { title, category }];
        });
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to add task.",
      );
    }
  }

  /**
   * Toggles a persisted daily task.
   */
  async function handleToggleTask(id: string) {
    const task = tasks.find((item) => item.id === id);
    if (!task) {
      return;
    }

    try {
      setError(null);
      const updatedTask = await updateDailyTaskCompletion(id, !task.completed);
      dispatch(replaceTask(updatedTask));

      if (!task.completed && updatedTask.completed) {
        const matchedHabits = habits.filter(
          (habit) =>
            habit.title.trim().toLowerCase() ===
            task.title.trim().toLowerCase(),
        );
        if (matchedHabits.length > 0) {
          for (const habit of matchedHabits) {
            await toggleHabitCompletion(habit.id, true);
          }
          const refreshedHabits = await listHabits();
          dispatch(setHabits(refreshedHabits));
        }
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to update task.",
      );
    }
  }

  /**
   * Deletes a persisted daily task.
   */
  async function handleDeleteTask(id: string) {
    try {
      setError(null);
      await deleteDailyTask(id);
      dispatch(removeTask(id));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to delete task.",
      );
    }
  }

  /**
   * Updates daily task title/category.
   */
  async function handleEditTask(
    id: string,
    title: string,
    category: DailyTaskCategory,
    options?: {
      goalId?: string | null;
      subCategory?: string | null;
      weekTag?: WeekTag | null;
      taskDate?: string | null;
    },
  ) {
    try {
      setError(null);
      const isKidsTask =
        category === "family" && options?.subCategory === "kids";
      const resolvedWeekTag = isKidsTask
        ? (options?.weekTag ?? getWeekOfMonth(new Date()))
        : null;
      const updatedTask = await updateDailyTask(id, {
        title,
        category,
        subCategory: options?.subCategory ?? null,
        weekTag: resolvedWeekTag,
        taskDate: options?.taskDate ?? null,
      });
      dispatch(replaceTask(updatedTask));

      if (
        options &&
        (options.goalId ?? null) !== (updatedTask.goalId ?? null)
      ) {
        const linked = await updateDailyTaskGoalLink(id, {
          goalId: options.goalId ?? null,
          weekTag: resolvedWeekTag,
        });
        dispatch(replaceTask(linked));
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to update task.",
      );
    }
  }

  function toggleRecurringTemplate(
    taskTitle: string,
    category: DailyTaskCategory,
    enabled: boolean,
  ) {
    setRecurringTemplates((current) => {
      if (enabled) {
        const exists = current.some(
          (template) =>
            template.title.trim().toLowerCase() ===
            taskTitle.trim().toLowerCase(),
        );
        if (exists) {
          return current;
        }
        return [...current, { title: taskTitle, category }];
      }
      return current.filter(
        (template) =>
          template.title.trim().toLowerCase() !==
          taskTitle.trim().toLowerCase(),
      );
    });
  }

  /**
   * Completes all incomplete tasks in the Daily Planner.
   */
  async function handleCompleteAllTasks() {
    try {
      setError(null);
      const incompleteTasks = sortedTodaysTasks.filter(
        (task) => !task.completed,
      );
      for (const task of incompleteTasks) {
        const updatedTask = await updateDailyTaskCompletion(task.id, true);
        dispatch(replaceTask(updatedTask));

        // Also update matched habits
        const matchedHabits = habits.filter(
          (habit) =>
            habit.title.trim().toLowerCase() ===
            task.title.trim().toLowerCase(),
        );
        if (matchedHabits.length > 0) {
          for (const habit of matchedHabits) {
            await toggleHabitCompletion(habit.id, true);
          }
        }
      }

      // Refresh habits list
      const refreshedHabits = await listHabits();
      dispatch(setHabits(refreshedHabits));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to complete all tasks.",
      );
    }
  }

  /**
   * Loads AI suggestions and caches them for this browser session.
   */
  // Generated by GitHub Copilot
  async function loadSuggestedTasks(forceRefresh = false) {
    if (activeMilestoneGoals.length === 0) {
      setSuggestedTasks([]);
      setSuggestionsError(null);
      return;
    }

    if (!forceRefresh && typeof window !== "undefined") {
      const cached = window.sessionStorage.getItem(suggestionsCacheKey);
      if (cached) {
        try {
          setSuggestedTasks(JSON.parse(cached) as SuggestedTaskItem[]);
          setSuggestionsError(null);
          return;
        } catch {
          window.sessionStorage.removeItem(suggestionsCacheKey);
        }
      }
    }

    try {
      setSuggestionsLoading(true);
      setSuggestionsError(null);

      const response = await fetch("/api/task-suggestions", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          goals: activeMilestoneGoals.map((goal) => ({
            goalId: goal.id,
            title: goal.title,
            category: goal.category,
            subCategory: goal.subCategory ?? null,
          })),
          recentTasks: recentTaskTitles,
          difficultyHint,
        }),
      });

      if (!response.ok) {
        throw new Error(
          `Task suggestions failed with status ${response.status}`,
        );
      }

      const payload = (await response.json()) as SuggestedTaskGroup[];
      const flattened: SuggestedTaskItem[] = [];
      const seen = new Set<string>();

      payload.forEach((group) => {
        const linkedGoal = group.goalId
          ? activeMilestoneGoals.find((goal) => goal.id === group.goalId)
          : activeMilestoneGoals.find((goal) => goal.title === group.goalTitle);

        if (!linkedGoal) {
          return;
        }

        group.suggestions.slice(0, 3).forEach((title) => {
          const normalizedTitle = title.trim();
          const key = `${linkedGoal.id}:${normalizedTitle.toLowerCase()}`;
          if (!normalizedTitle || seen.has(key)) {
            return;
          }
          seen.add(key);
          flattened.push({
            goalId: linkedGoal.id,
            goalTitle: linkedGoal.title,
            title: normalizedTitle,
            category: linkedGoal.category,
          });
        });
      });

      const limited = flattened.slice(0, 5);
      setSuggestedTasks(limited);

      if (typeof window !== "undefined") {
        window.sessionStorage.setItem(
          suggestionsCacheKey,
          JSON.stringify(limited),
        );
      }
    } catch (suggestionsLoadError) {
      setSuggestionsError(
        suggestionsLoadError instanceof Error
          ? suggestionsLoadError.message
          : "Failed to load suggested tasks.",
      );
    } finally {
      setSuggestionsLoading(false);
    }
  }

  /**
   * Creates a starter set of recurring milestone goals (one per pillar) for suggestion generation.
   */
  // Generated by GitHub Copilot
  async function handleCreateStarterMilestones() {
    if (!user) {
      return;
    }

    const starterGoals: Array<{
      title: string;
      description: string;
      category: DailyTaskCategory;
      repeat: "weekly" | "monthly";
    }> = [
      {
        title: "Career Learning Sprint",
        description: "Complete focused skill-building sessions every week.",
        category: "career",
        repeat: "weekly",
      },
      {
        title: "Family Connection Block",
        description: "Create intentional family quality time each week.",
        category: "family",
        repeat: "weekly",
      },
      {
        title: "Finance Savings Discipline",
        description: "Maintain monthly savings momentum with structured reviews.",
        category: "finance",
        repeat: "monthly",
      },
      {
        title: "Peace Recovery Routine",
        description: "Protect weekly recovery and mental reset rituals.",
        category: "peace",
        repeat: "weekly",
      },
    ];

    try {
      setError(null);
      const existingTitles = new Set(
        goals.map((goal) => goal.title.trim().toLowerCase()),
      );

      let createdCount = 0;
      for (const starter of starterGoals) {
        if (existingTitles.has(starter.title.trim().toLowerCase())) {
          continue;
        }

        const createdGoal = await createGoal(user.id, {
          title: starter.title,
          description: starter.description,
          category: starter.category,
          targetDate: null,
          goalType: "milestone",
          period: starter.repeat === "weekly" ? "weekly" : "monthly",
          repeat: starter.repeat,
          levelCurrent: 1,
          levelTarget: 5,
        });

        dispatch(addGoal(createdGoal));
        createdCount += 1;
      }

      if (createdCount === 0) {
        setError("Starter milestone goals already exist.");
      }
    } catch (seedError) {
      setError(
        seedError instanceof Error
          ? seedError.message
          : "Failed to create starter milestone goals.",
      );
    }
  }

  useEffect(() => {
    void loadSuggestedTasks();
  }, [suggestionsCacheKey]);

  return (
    <Stack spacing={3}>
      <PageHeader
        title="Daily Planner"
        description="A short, pillar-based checklist for the day with optional sub-categories for family and peace."
      />
      {error ? <Alert severity="error">{error}</Alert> : null}
      <Card>
        <CardContent>
          <Stack
            direction={{ xs: "column", sm: "row" }}
            spacing={2}
            alignItems={{ xs: "flex-start", sm: "center" }}
            justifyContent="space-between"
          >
            <Stack spacing={0.5}>
              <Typography variant="h6" gutterBottom={false}>
                Category Overview
              </Typography>
              <Typography variant="body2" color="text.secondary">
                Week {weekNumber} of month. Kids focus: {weekFocus.focus}.
              </Typography>
              <Typography variant="caption" color="text.secondary">
                Total: {visibleTasks.length} / Completed:{" "}
                {visibleTasks.filter((t) => t.completed).length}
              </Typography>
            </Stack>
            <Chip
              label={weekTag.replace("week", "Week ")}
              color="primary"
              variant="filled"
              sx={{ fontWeight: 700 }}
            />
          </Stack>
          <Grid container spacing={1.5} sx={{ mt: 1 }}>
            {Object.entries(counts).map(([cat, count]) => (
              <Grid item key={cat}>
                <Chip
                  label={`${cat}: ${count}`}
                  color="primary"
                  variant="outlined"
                />
              </Grid>
            ))}
          </Grid>
        </CardContent>
      </Card>
      {!reminderDismissed && todaysTasks.length > 2 && completionRate < 50 ? (
        <Alert
          severity="info"
          action={
            <Button size="small" onClick={() => setReminderDismissed(true)}>
              Dismiss
            </Button>
          }
        >
          Gentle reminder: complete one more task now to keep your day moving
          calmly.
        </Alert>
      ) : null}
      <Box
        sx={{
          display: "grid",
          gap: 3,
          gridTemplateColumns: { xs: "1fr", lg: "1fr 1fr" },
          alignItems: "stretch",
        }}
      >
        <Box>
          <Card sx={{ height: "100%" }}>
            <CardContent>
              <Stack spacing={1.25}>
                <Stack
                  direction="row"
                  alignItems="center"
                  justifyContent="space-between"
                >
                  <Typography variant="h6">Quick Mode</Typography>
                  <Typography variant="caption" color="text.secondary">
                    {todaysTasks.filter((t) => t.completed).length}/
                    {todaysTasks.length}
                  </Typography>
                </Stack>
                <Stack
                  direction="row"
                  alignItems="center"
                  justifyContent="space-between"
                >
                  <Typography color="text.secondary">
                    One-tap complete for today's tasks
                  </Typography>
                  <Switch
                    checked={quickMode}
                    onChange={(event) => setQuickMode(event.target.checked)}
                  />
                </Stack>
                {quickMode ? (
                  <Stack spacing={1}>
                    {todaysTasks.length === 0 ? (
                      <Typography color="text.secondary">
                        No tasks for today yet. Add one and keep it simple.
                      </Typography>
                    ) : (
                      todaysTasks.map((task) => (
                        <Button
                          key={task.id}
                          variant={task.completed ? "outlined" : "contained"}
                          color={task.completed ? "success" : "primary"}
                          onClick={() => void handleToggleTask(task.id)}
                          sx={{ justifyContent: "flex-start" }}
                        >
                          {task.completed ? "Done: " : "Tap to complete: "}
                          {task.title}
                        </Button>
                      ))
                    )}
                  </Stack>
                ) : (
                  <Typography color="text.secondary">
                    Quick mode is off. Turn it on for one-screen completion.
                  </Typography>
                )}
              </Stack>
            </CardContent>
          </Card>
        </Box>
        <Box>
          <Card sx={{ height: "100%" }}>
            <CardContent>
              <Stack spacing={1.25}>
                <Typography variant="h6">
                  Completion Rate Trend (Last 7 Days)
                </Typography>
                <Typography color="text.secondary">
                  Today: {completionRate}% complete
                </Typography>
                <ResponsiveContainer width="100%" height={220}>
                  <BarChart data={trendData}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="day" />
                    <YAxis domain={[0, 100]} />
                    <Tooltip />
                    <Bar
                      dataKey="completionRate"
                      fill="#1E88E5"
                      radius={[6, 6, 0, 0]}
                    />
                  </BarChart>
                </ResponsiveContainer>
              </Stack>
            </CardContent>
          </Card>
        </Box>
      </Box>

      <Box
        sx={{
          display: "grid",
          gap: 3,
          gridTemplateColumns: { xs: "1fr", lg: "1fr 1fr" },
          alignItems: "stretch",
        }}
      >
        <Card sx={{ height: "fit-content" }}>
          <CardContent>
            <Stack spacing={1.25}>
              <Stack
                direction="row"
                alignItems="center"
                justifyContent="space-between"
              >
                <div>
                  <Stack direction="row" spacing={1} alignItems="center">
                    <Typography variant="h6">Repeat Task Configuration</Typography>
                    <Chip
                      label={`${repeatConfigTasks.length} tasks`}
                      size="small"
                      variant="outlined"
                    />
                  </Stack>
                  {!repeatExpanded && (
                    <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                      Mark any existing task to repeat daily automatically.
                    </Typography>
                  )}
                </div>
                <IconButton
                  size="small"
                  onClick={() => setRepeatExpanded((prev) => !prev)}
                  aria-label={
                    repeatExpanded
                      ? "Collapse repeat task configuration"
                      : "Expand repeat task configuration"
                  }
                  aria-expanded={repeatExpanded}
                >
                  {repeatExpanded ? (
                    <ExpandLessRoundedIcon />
                  ) : (
                    <ExpandMoreRoundedIcon />
                  )}
                </IconButton>
              </Stack>
              <Collapse in={repeatExpanded} timeout="auto">
                <Stack spacing={1.25} sx={{ mt: 1 }}>
                  <Box
                    sx={{
                      maxHeight: 300,
                      overflowY: "auto",
                      pr: 1,
                      "&::-webkit-scrollbar": {
                        width: "6px",
                      },
                      "&::-webkit-scrollbar-track": {
                        background: "transparent",
                      },
                      "&::-webkit-scrollbar-thumb": {
                        background: "rgba(0, 0, 0, 0.2)",
                        borderRadius: "3px",
                        "&:hover": {
                          background: "rgba(0, 0, 0, 0.3)",
                        },
                      },
                    }}
                  >
                    <Grid container spacing={1.2}>
                      {repeatConfigTasks.map((task) => {
                        const recurring = recurringTemplates.some(
                          (template) =>
                            template.title.trim().toLowerCase() ===
                            task.title.trim().toLowerCase(),
                        );
                        return (
                          <Grid item xs={12} key={task.title.toLowerCase()}>
                            <Stack
                              direction="row"
                              alignItems="center"
                              justifyContent="space-between"
                              sx={{
                                px: 1,
                                py: 0.5,
                                borderRadius: 2,
                                bgcolor: "rgba(255,255,255,0.55)",
                              }}
                            >
                              <Typography variant="body2">{task.title}</Typography>
                              <Switch
                                checked={recurring}
                                onChange={(event) =>
                                  toggleRecurringTemplate(
                                    task.title,
                                    task.category,
                                    event.target.checked,
                                  )
                                }
                              />
                            </Stack>
                          </Grid>
                        );
                      })}
                    </Grid>
                  </Box>
                </Stack>
              </Collapse>
            </Stack>
          </CardContent>
        </Card>

        <Card sx={{ height: "fit-content" }}>
          <CardContent sx={{ display: "flex", flexDirection: "column" }}>
            <Stack spacing={1.25}>
              <Stack
                direction="row"
                alignItems="center"
                justifyContent="space-between"
              >
                <div>
                  <Typography variant="h6">Suggested Tasks</Typography>
                  {!suggestedTasksExpanded && (
                    <Typography variant="body2" color="text.secondary" sx={{ mt: 0.5 }}>
                      {mergedSuggestedTasks.length} suggestions available
                    </Typography>
                  )}
                </div>
                <IconButton
                  size="small"
                  onClick={() => setSuggestedTasksExpanded((prev) => !prev)}
                  aria-label={
                    suggestedTasksExpanded
                      ? "Collapse suggested tasks"
                      : "Expand suggested tasks"
                  }
                  aria-expanded={suggestedTasksExpanded}
                >
                  {suggestedTasksExpanded ? (
                    <ExpandLessRoundedIcon />
                  ) : (
                    <ExpandMoreRoundedIcon />
                  )}
                </IconButton>
              </Stack>
              <Collapse in={suggestedTasksExpanded} timeout="auto">
                <Stack spacing={1}>
                  <Stack
                    direction={{ xs: "column", sm: "row" }}
                    alignItems={{ xs: "flex-start", sm: "center" }}
                    justifyContent="flex-start"
                    spacing={1}
                  >
                    <Button
                      size="small"
                      variant="outlined"
                      onClick={() => void loadSuggestedTasks(true)}
                      disabled={
                        suggestionsLoading || activeMilestoneGoals.length === 0
                      }
                    >
                      Refresh Suggestions
                    </Button>
                    {mergedSuggestedTasks.length > 0 && (
                      <Button
                        size="small"
                        variant="outlined"
                        onClick={() => {
                          // Add all suggested tasks to the planner
                          mergedSuggestedTasks.forEach((suggestion) => {
                            setSuggestionPrefill({
                              title: suggestion.title,
                              category: suggestion.category,
                              goalId: suggestion.goalId,
                            });
                          });
                        }}
                      >
                        Add All
                      </Button>
                    )}
                  </Stack>

                  {activeMilestoneGoals.length === 0 && activeMonthlyGoals.length === 0 ? (
                    <Stack spacing={1}>
                      <Typography color="text.secondary" variant="body2">
                        Create a recurring milestone goal to get AI suggestions.
                      </Typography>
                      <Button
                        size="small"
                        variant="contained"
                        onClick={() => void handleCreateStarterMilestones()}
                        sx={{ alignSelf: "flex-start" }}
                      >
                        Create Starter Milestones
                      </Button>
                    </Stack>
                  ) : null}

                  {suggestionsLoading ? (
                    <Typography color="text.secondary" variant="body2">
                      Generating practical suggestions...
                    </Typography>
                  ) : null}

                  {suggestionsError ? (
                    <Alert
                      severity="warning"
                      action={
                        <Button
                          color="inherit"
                          size="small"
                          onClick={() => void loadSuggestedTasks(true)}
                        >
                          Retry
                        </Button>
                      }
                    >
                      {suggestionsError}
                    </Alert>
                  ) : null}

                  {!suggestionsLoading &&
                  !suggestionsError &&
                  mergedSuggestedTasks.length === 0 &&
                  (activeMilestoneGoals.length > 0 || activeMonthlyGoals.length > 0) ? (
                    <Typography color="text.secondary" variant="body2">
                      No suggestions available right now. Try refresh.
                    </Typography>
                  ) : null}

                  {!suggestionsLoading && !suggestionsError && mergedSuggestedTasks.length > 0 ? (
                <Box
                  sx={{
                    maxHeight: 350,
                    overflowY: "auto",
                    pr: 1,
                    "&::-webkit-scrollbar": {
                      width: "6px",
                    },
                    "&::-webkit-scrollbar-track": {
                      background: "transparent",
                    },
                    "&::-webkit-scrollbar-thumb": {
                      background: "rgba(0, 0, 0, 0.2)",
                      borderRadius: "3px",
                      "&:hover": {
                        background: "rgba(0, 0, 0, 0.3)",
                      },
                    },
                  }}
                >
                  <Stack spacing={1}>
                    {mergedSuggestedTasks.map((suggestion) => (
                      <Stack
                        key={`${suggestion.goalId}:${suggestion.title}`}
                        direction={{ xs: "column", sm: "row" }}
                        alignItems={{ xs: "flex-start", sm: "center" }}
                        justifyContent="space-between"
                        spacing={1}
                        sx={{
                          p: 1.25,
                          borderRadius: 1.5,
                          border: "1px solid",
                          borderColor: "divider",
                          flexShrink: 0,
                        }}
                      >
                        <Stack spacing={0.25}>
                          <Typography sx={{ fontWeight: 600 }}>
                            {suggestion.title}
                          </Typography>
                          <Typography variant="caption" color="text.secondary">
                            Goal: {suggestion.goalTitle}
                          </Typography>
                        </Stack>
                        <Button
                          size="small"
                          variant="contained"
                          sx={{ flexShrink: 0 }}
                          onClick={() =>
                            setSuggestionPrefill({
                              title: suggestion.title,
                              category: suggestion.category,
                              goalId: suggestion.goalId,
                            })
                          }
                        >
                          + Add
                        </Button>
                      </Stack>
                    ))}
                  </Stack>
                </Box>
                  ) : null}
                </Stack>
              </Collapse>
            </Stack>
          </CardContent>
        </Card>
      </Box>
      <Stack spacing={0.75}>
        <Card>
          <CardContent sx={{ pb: 0.75 }}>
            <Stack
              direction={{ xs: "column", sm: "row" }}
              spacing={2}
              alignItems={{ xs: "flex-start", sm: "center" }}
              justifyContent="space-between"
              sx={{ mb: "5px" }}
            >
              <Typography variant="h6">
                Daily Planner (
                {sortedTodaysTasks.filter((t) => t.completed).length}/
                {sortedTodaysTasks.length})
              </Typography>
              <Stack
                direction={{ xs: "column", sm: "row" }}
                spacing={1.5}
                sx={{ width: { xs: "100%", sm: "auto" } }}
              >
                <Button
                  variant="outlined"
                  size="small"
                  onClick={handleCompleteAllTasks}
                  disabled={
                    sortedTodaysTasks.length === 0 ||
                    sortedTodaysTasks.every((t) => t.completed)
                  }
                  sx={{ minWidth: { xs: "100%", sm: 120 } }}
                >
                  Complete All
                </Button>
                <TextField
                  select
                  size="small"
                  label="View"
                  value={plannerView}
                  onChange={(e) =>
                    setPlannerView(e.target.value as "today" | "all")
                  }
                  sx={{ minWidth: { xs: "100%", sm: 120 } }}
                >
                  <MenuItem value="today">Today</MenuItem>
                  <MenuItem value="all">All Tasks</MenuItem>
                </TextField>
                <TextField
                  select
                  size="small"
                  label="Goal"
                  value={selectedGoalId ?? ""}
                  onChange={(e) => setSelectedGoalId(e.target.value || null)}
                  sx={{ minWidth: { xs: "100%", sm: 170 } }}
                >
                  <MenuItem value="">All Tasks</MenuItem>
                  {goals.map((goal) => (
                    <MenuItem key={goal.id} value={goal.id}>
                      {goal.title}
                    </MenuItem>
                  ))}
                </TextField>
                <TextField
                  select
                  size="small"
                  label="Sort by"
                  value={taskSortBy}
                  onChange={(e) =>
                    setTaskSortBy(
                      e.target.value as "category-asc" | "category-desc",
                    )
                  }
                  sx={{ minWidth: { xs: "100%", sm: 160 } }}
                >
                  <MenuItem value="category-asc">Category (A-Z)</MenuItem>
                  <MenuItem value="category-desc">Category (Z-A)</MenuItem>
                </TextField>
              </Stack>
            </Stack>
          </CardContent>
          <DailyChecklist
            title=""
            tasks={sortedTodaysTasks}
            goals={goals}
            prefillDraft={suggestionPrefill}
            onPrefillConsumed={() => setSuggestionPrefill(null)}
            listMaxHeight={400}
            onToggle={handleToggleTask}
            onDelete={handleDeleteTask}
            onAdd={handleAddTask}
            onEdit={handleEditTask}
          />
        </Card>
      </Stack>
    </Stack>
  );
}

