"use client";

import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import { Alert, Box, Button, Card, CardContent, Chip, Collapse, Divider, IconButton, Stack, TextField, Typography } from "@mui/material";
import ExpandLessRoundedIcon from "@mui/icons-material/ExpandLessRounded";
import ExpandMoreRoundedIcon from "@mui/icons-material/ExpandMoreRounded";
import {
  CartesianGrid,
  Line,
  LineChart,
  PolarAngleAxis,
  PolarGrid,
  PolarRadiusAxis,
  Radar,
  RadarChart,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import PageHeader from "@/components/common/PageHeader";
import WeeklyReviewForm from "@/components/dashboard/WeeklyReviewForm";
import { useAuth } from "@/lib/auth-context";
import { createWeeklyReview } from "@/lib/persistence";
import { getLatestWeeklyReview } from "@/lib/score";
import { getWeeklySuggestionHistory, saveWeeklySuggestionHistory } from "@/lib/useWeeklySummary";
import { addWeeklyReview } from "@/store/slices/weeklyReviewSlice";
import { AppDispatch, RootState } from "@/store/store";

/**
 * Renders the weekly review workflow with score entry and visual analysis.
 */
export default function WeeklyReviewPage() {
  const dispatch = useDispatch<AppDispatch>();
  const { user } = useAuth();
  const [error, setError] = useState<string | null>(null);
  const [suggestionHistory, setSuggestionHistory] = useState<ReturnType<typeof getWeeklySuggestionHistory>>([]);
  const [historyMonth, setHistoryMonth] = useState(() => new Date().toISOString().slice(0, 7));
  const [copiedSuggestionId, setCopiedSuggestionId] = useState<string | null>(null);
  const [notesExpanded, setNotesExpanded] = useState(true);
  const [radarExpanded, setRadarExpanded] = useState(true);
  const [trendExpanded, setTrendExpanded] = useState(true);
  const reviews = useSelector((state: RootState) => state.weeklyReviews.reviews);
  const latestReview = getLatestWeeklyReview(reviews);
  const radarData = [
    { subject: "Career", score: latestReview?.careerScore ?? 0 },
    { subject: "Family", score: latestReview?.familyScore ?? 0 },
    { subject: "Finance", score: latestReview?.financeScore ?? 0 },
    { subject: "Peace", score: latestReview?.peaceScore ?? 0 },
  ];

  // Generated by GitHub Copilot - Weekly improvement trend insight based on recent reviews
  const trendInsight = useMemo(() => {
    const ordered = [...reviews].sort(
      (a, b) => new Date(a.weekStart).getTime() - new Date(b.weekStart).getTime(),
    );

    if (ordered.length < 2) {
      return {
        direction: "neutral" as const,
        delta: 0,
        percentDelta: 0,
        message: "Add at least two weekly reviews to see your improvement trend.",
      };
    }

    const recent = ordered.slice(-4);
    const first = recent[0].lifeBalanceScore;
    const last = recent[recent.length - 1].lifeBalanceScore;
    const delta = Number((last - first).toFixed(1));
    const percentDelta = first > 0 ? Number((((last - first) / first) * 100).toFixed(0)) : 0;

    if (delta > 0.2) {
      return {
        direction: "up" as const,
        delta,
        percentDelta,
        message: `Your last ${recent.length}-week trend is improving (+${delta}). Keep compounding what is working.`,
      };
    }

    if (delta < -0.2) {
      return {
        direction: "down" as const,
        delta,
        percentDelta,
        message: `Your last ${recent.length}-week trend is slipping (${delta}). Revisit routines in your weakest pillar.`,
      };
    }

    return {
      direction: "neutral" as const,
      delta,
      percentDelta,
      message: `Your last ${recent.length}-week trend is stable (${delta >= 0 ? "+" : ""}${delta}). Focus on one small consistency win next week.`,
    };
  }, [reviews]);

  const sparklineData = useMemo(() => {
    return [...reviews]
      .sort((a, b) => new Date(a.weekStart).getTime() - new Date(b.weekStart).getTime())
      .slice(-8)
      .map((review) => ({
        week: review.weekStart.slice(5),
        score: review.lifeBalanceScore,
      }));
  }, [reviews]);

  const visibleSuggestionHistory = useMemo(() => {
    const scoped = historyMonth
      ? suggestionHistory.filter((entry) => entry.weekStart.startsWith(historyMonth))
      : suggestionHistory;
    return scoped.slice(0, 6);
  }, [historyMonth, suggestionHistory]);

  useEffect(() => {
    if (!user) {
      setSuggestionHistory([]);
      return;
    }

    setSuggestionHistory(getWeeklySuggestionHistory(user.id));
  }, [reviews, user]);

  /**
   * Creates a persisted weekly review.
   */
  async function handleSubmit(payload: {
    weekStart: string;
    careerScore: number;
    familyScore: number;
    financeScore: number;
    peaceScore: number;
    notes: string;
  }) {
    if (!user) {
      return;
    }

    try {
      setError(null);
      const review = await createWeeklyReview(user.id, payload);
      dispatch(addWeeklyReview(review));

      // Generated by GitHub Copilot - Save final user note along with AI suggestion for this week
      const aiMatch = payload.notes.match(/💡\s*AI Suggestion:\s*([\s\S]*)$/);
      const cleanedNotes = payload.notes.replace(/💡\s*AI Suggestion:\s*[\s\S]*$/, "").trim();
      saveWeeklySuggestionHistory({
        userId: user.id,
        weekStart: payload.weekStart,
        notesText: cleanedNotes,
        suggestion: aiMatch?.[1]?.trim(),
        lifeBalanceScore: review.lifeBalanceScore,
      });

      setSuggestionHistory(getWeeklySuggestionHistory(user.id));
    } catch (submissionError) {
      setError(submissionError instanceof Error ? submissionError.message : "Failed to save weekly review.");
    }
  }

  async function handleCopySuggestion(entryId: string, suggestion: string) {
    try {
      await navigator.clipboard.writeText(suggestion);
      setCopiedSuggestionId(entryId);
      setTimeout(() => {
        setCopiedSuggestionId((current) => (current === entryId ? null : current));
      }, 1800);
    } catch {
      setError("Could not copy suggestion. Please copy manually.");
    }
  }

  return (
    <Stack spacing={3} sx={{ py: { xs: 1.5, md: 3 } }}>
      <PageHeader
        title="Weekly Review"
        description="Score the four areas from 1 to 10, calculate the average, and track the direction over time."
      />
      {error ? <Alert severity="error">{error}</Alert> : null}
      <WeeklyReviewForm onSubmit={handleSubmit} />

      <Card>
        <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
          <Stack spacing={1.5}>
            <Typography variant="h5">Improvement Trend</Typography>
            <Stack direction={{ xs: "column", sm: "row" }} spacing={1} alignItems={{ xs: "flex-start", sm: "center" }}>
              <Chip
                label={
                  trendInsight.direction === "up"
                    ? "Improving"
                    : trendInsight.direction === "down"
                    ? "Needs Attention"
                    : "Stable"
                }
                color={
                  trendInsight.direction === "up"
                    ? "success"
                    : trendInsight.direction === "down"
                    ? "warning"
                    : "default"
                }
                size="small"
              />
              <Chip
                label={`${trendInsight.percentDelta >= 0 ? "+" : ""}${trendInsight.percentDelta}%`}
                variant="outlined"
                color={
                  trendInsight.direction === "up"
                    ? "success"
                    : trendInsight.direction === "down"
                    ? "warning"
                    : "default"
                }
                size="small"
              />
              <Typography variant="body2" color="text.secondary">
                {trendInsight.message}
              </Typography>
            </Stack>
            <Stack spacing={0.5}>
              <Typography variant="caption" color="text.secondary">
                Last {sparklineData.length} weeks quick trend
              </Typography>
              <ResponsiveContainer width="100%" height={72}>
                <LineChart data={sparklineData}>
                  <Line type="monotone" dataKey="score" stroke="#2E7D32" strokeWidth={2.5} dot={false} />
                  <YAxis hide domain={[0, 10]} />
                  <Tooltip />
                </LineChart>
              </ResponsiveContainer>
            </Stack>
          </Stack>
        </CardContent>
      </Card>

      <Card>
        <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
          <Stack spacing={1.5}>
            <Stack direction={{ xs: "column", sm: "row" }} spacing={1} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }}>
              <Stack direction="row" alignItems="center" spacing={1}>
                <Typography variant="h5">Notes History</Typography>
                {!notesExpanded && (
                  <Typography variant="caption" color="text.secondary">
                    {visibleSuggestionHistory.length} notes
                  </Typography>
                )}
              </Stack>
              <Stack direction={{ xs: "column", sm: "row" }} spacing={1} alignItems={{ xs: "flex-start", sm: "center" }}>
                <TextField
                  type="month"
                  label="Filter month"
                  value={historyMonth}
                  onChange={(event) => setHistoryMonth(event.target.value)}
                  InputLabelProps={{ shrink: true }}
                  sx={{ minWidth: { xs: "100%", sm: 180 } }}
                />
                <Button variant="text" size="small" onClick={() => setHistoryMonth("")}>Show all</Button>
                <IconButton
                  size="small"
                  onClick={() => setNotesExpanded((prev) => !prev)}
                  aria-label={notesExpanded ? "Collapse notes history" : "Expand notes history"}
                  aria-expanded={notesExpanded}
                >
                  {notesExpanded ? <ExpandLessRoundedIcon /> : <ExpandMoreRoundedIcon />}
                </IconButton>
              </Stack>
            </Stack>
            <Collapse in={notesExpanded} timeout="auto">
              <Box
                sx={{
                  maxHeight: 400,
                  overflowY: "auto",
                  pr: 1,
                  "&::-webkit-scrollbar": {
                    width: "6px",
                  },
                  "&::-webkit-scrollbar-track": {
                    background: "transparent",
                  },
                  "&::-webkit-scrollbar-thumb": {
                    background: "rgba(0, 0, 0, 0.2)",
                    borderRadius: "3px",
                    "&:hover": {
                      background: "rgba(0, 0, 0, 0.3)",
                    },
                  },
                }}
              >
                {visibleSuggestionHistory.length === 0 ? (
                  <Typography variant="body2" color="text.secondary">
                    Your generated weekly note suggestions will appear here after summary generation.
                  </Typography>
                ) : (
                  visibleSuggestionHistory.map((entry, index) => (
                    <Stack key={entry.id} spacing={0.5}>
                      {/** Show only one note text to avoid redundant entries */}
                      {(() => {
                        const historyText = (entry.notesText || entry.suggestion || "").trim();
                        return (
                          <>
                        <Stack direction="row" spacing={1} justifyContent="space-between" alignItems="center">
                          <Typography variant="body2" sx={{ fontWeight: 700 }}>
                            Week of {entry.weekStart} • Score {entry.lifeBalanceScore} • Completion {entry.completionRate}%
                          </Typography>
                          <Button
                            size="small"
                            variant="outlined"
                            onClick={() => void handleCopySuggestion(entry.id, historyText)}
                          >
                            {copiedSuggestionId === entry.id ? "Copied" : "Copy"}
                          </Button>
                        </Stack>
                        <Typography variant="caption" color="text.secondary" sx={{ fontStyle: "italic" }}>
                          Note:
                        </Typography>
                        <Typography variant="body2" color="text.secondary">
                          {historyText}
                        </Typography>
                          </>
                        );
                      })()}
                      {index < visibleSuggestionHistory.length - 1 ? <Divider /> : null}
                    </Stack>
                  ))
                )}
              </Box>
            </Collapse>
          </Stack>
        </CardContent>
      </Card>

      <Stack direction={{ xs: "column", lg: "row" }} spacing={3} alignItems="stretch">
        <Card sx={{ flex: 1, minWidth: 0, height: "fit-content" }}>
          <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
            <Stack spacing={1.5}>
              <Stack direction="row" alignItems="center" justifyContent="space-between">
                <Typography variant="h5">Latest Review Radar</Typography>
                <IconButton
                  size="small"
                  onClick={() => setRadarExpanded((prev) => !prev)}
                  aria-label={radarExpanded ? "Collapse chart" : "Expand chart"}
                  aria-expanded={radarExpanded}
                >
                  {radarExpanded ? <ExpandLessRoundedIcon /> : <ExpandMoreRoundedIcon />}
                </IconButton>
              </Stack>
              <Collapse in={radarExpanded} timeout="auto">
                <ResponsiveContainer width="100%" height={320}>
                  <RadarChart data={radarData}>
                    <PolarGrid />
                    <PolarAngleAxis dataKey="subject" />
                    <PolarRadiusAxis domain={[0, 10]} />
                    <Tooltip />
                    <Radar
                      dataKey="score"
                      stroke="#43A047"
                      fill="#81C784"
                      fillOpacity={0.55}
                    />
                  </RadarChart>
                </ResponsiveContainer>
              </Collapse>
            </Stack>
          </CardContent>
        </Card>
        <Card sx={{ flex: 1, minWidth: 0, height: "fit-content" }}>
          <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
            <Stack spacing={1.5}>
              <Stack direction="row" alignItems="center" justifyContent="space-between">
                <Typography variant="h5">Score Trend</Typography>
                <IconButton
                  size="small"
                  onClick={() => setTrendExpanded((prev) => !prev)}
                  aria-label={trendExpanded ? "Collapse chart" : "Expand chart"}
                  aria-expanded={trendExpanded}
                >
                  {trendExpanded ? <ExpandLessRoundedIcon /> : <ExpandMoreRoundedIcon />}
                </IconButton>
              </Stack>
              <Collapse in={trendExpanded} timeout="auto">
                <ResponsiveContainer width="100%" height={320}>
                  <LineChart data={reviews.slice().reverse()}>
                    <CartesianGrid strokeDasharray="3 3" />
                    <XAxis dataKey="weekStart" />
                    <YAxis domain={[0, 10]} />
                    <Tooltip />
                    <Line
                      type="monotone"
                      dataKey="lifeBalanceScore"
                      stroke="#1E88E5"
                      strokeWidth={3}
                    />
                  </LineChart>
                </ResponsiveContainer>
              </Collapse>
            </Stack>
          </CardContent>
        </Card>
      </Stack>
      </Stack>
  );
}
