// Generated by GitHub Copilot
export interface ModuleQuickGuide {
  focus: string;
  inputs: string[];
  outputs: string[];
}

// Generated by GitHub Copilot
export const MODULE_QUICK_GUIDE: Record<string, ModuleQuickGuide> = {
  "/dashboard": {
    focus: "Get a fast health check of your week across all pillars.",
    inputs: [
      "No mandatory input. Use quick actions, filters, and task toggles.",
      "Optionally link tasks to goals for better tracking.",
    ],
    outputs: [
      "Life balance snapshot and trend cards.",
      "Actionable next steps for today.",
    ],
  },
  "/daily": {
    focus: "Plan a realistic day and complete pillar-linked tasks.",
    inputs: [
      "Add task title, category, and optional goal link.",
      "Use repeat settings for recurring daily actions.",
    ],
    outputs: [
      "Prioritized daily checklist and completion progress.",
      "Suggested tasks based on active goals and context.",
    ],
  },
  "/goals": {
    focus: "Turn long-term intent into clear, trackable commitments.",
    inputs: [
      "Create goals with type, period, and target details.",
      "Update levels, status, and supporting sub-tasks.",
    ],
    outputs: [
      "Structured goal hierarchy (master/milestone/task).",
      "Progress visibility and level movement over time.",
    ],
  },
  "/weekly-review": {
    focus: "Review the week honestly and reset the next one with clarity.",
    inputs: [
      "Score each pillar from 1 to 10.",
      "Add notes on what worked and what needs adjustment.",
    ],
    outputs: [
      "Weekly life balance score and trend visuals.",
      "Focused improvement suggestions for next week.",
    ],
  },
  "/monthly-review": {
    focus: "Capture monthly lessons and plan better next-month moves.",
    inputs: [
      "Record what improved, what did not, and level changes.",
      "Optionally regenerate AI-refined insights before saving.",
    ],
    outputs: [
      "Monthly reflection history and insights.",
      "Clear monthly adjustment direction.",
    ],
  },
  "/finance": {
    focus: "Track money flow and make calmer financial decisions.",
    inputs: [
      "Add entry type, amount, category, and optional notes.",
      "Keep entries regular for better pattern detection.",
    ],
    outputs: [
      "Savings and cash-flow visibility.",
      "Category-wise spending and trend awareness.",
    ],
  },
  "/habits": {
    focus: "Build consistency with repeatable behavior tracking.",
    inputs: [
      "Create habits with category and target frequency.",
      "Mark completion daily to maintain momentum.",
    ],
    outputs: [
      "Habit completion trend and streak confidence.",
      "Visibility into routines that support your pillars.",
    ],
  },
  "/kids": {
    focus: "Track meaningful child development observations weekly.",
    inputs: [
      "Log activity type, date, notes, and rating.",
      "Capture small observations consistently.",
    ],
    outputs: [
      "Progress patterns across behavior, study, and creativity.",
      "Data-backed weekly parenting focus areas.",
    ],
  },
  "/reflections": {
    focus: "Convert daily experience into learning and better tomorrow actions.",
    inputs: [
      "Write what went well, what you learned, and what to improve.",
      "Add mood score for better emotional trend tracking.",
    ],
    outputs: [
      "Reflection timeline with mood pattern visibility.",
      "Clear next-step mindset for the next day.",
    ],
  },
  "/garden": {
    focus: "Keep recurring home-care tasks simple and visible.",
    inputs: [
      "Add task name, due date, and optional details.",
      "Mark completion as work gets done.",
    ],
    outputs: [
      "Practical maintenance checklist.",
      "Lower clutter and fewer forgotten tasks.",
    ],
  },
  "/knowledge-base": {
    focus: "Quickly reference principles and workflows when unsure.",
    inputs: [
      "No form input needed.",
      "Browse sections based on your current challenge.",
    ],
    outputs: [
      "Fast context for daily, weekly, and monthly decisions.",
      "Reduced confusion during planning and reviews.",
    ],
  },
  "/user-guide": {
    focus: "Understand how to use each module effectively.",
    inputs: [
      "No mandatory input.",
      "Follow step-by-step guidance per module cadence.",
    ],
    outputs: [
      "Faster onboarding and less form confusion.",
      "More productive usage with fewer mistakes.",
    ],
  },
};
