// Generated by GitHub Copilot
export interface UserGuideSection {
  id: string;
  title: string;
  points: string[];
}

// Generated by GitHub Copilot
export const USER_GUIDE_SECTIONS: UserGuideSection[] = [
  {
    id: "introduction",
    title: "Introduction",
    points: [
      "Life Balance OS helps you manage career, family, finance, and peace in one place.",
      "Use it as a simple rhythm: plan daily, review weekly, improve monthly.",
      "Start small and stay consistent instead of trying to do everything at once.",
    ],
  },
  {
    id: "daily-routine",
    title: "Daily Routine",
    points: [
      "Morning: plan 3 key tasks linked to your active goals.",
      "During the day: complete tasks and keep your list realistic.",
      "Night: capture one reflection and prepare tomorrow with clarity.",
    ],
  },
  {
    id: "weekly-review",
    title: "Weekly Review",
    points: [
      "Score each pillar honestly based on your week.",
      "See what worked and what slipped without judgment.",
      "Pick one high-impact focus for the next week.",
    ],
  },
  {
    id: "monthly-review",
    title: "Monthly Review",
    points: [
      "Review weekly patterns from the full month.",
      "Identify one improvement area and one strength to keep.",
      "Adjust goals and task strategy for the next month.",
    ],
  },
  {
    id: "goals-system",
    title: "Goals System",
    points: [
      "Create milestone goals for long-term direction.",
      "Link daily tasks to goals so progress is measurable.",
      "Use levels to track growth from Level 1 to Level 5.",
    ],
  },
  {
    id: "kids-system",
    title: "Kids System (Weekly Rotation)",
    points: [
      "Use weekly focus tags to rotate themes for kids activities.",
      "Keep tasks small and age-appropriate.",
      "Track consistency rather than perfection.",
    ],
  },
  {
    id: "habits-peace",
    title: "Habits and Peace",
    points: [
      "Build repeatable routines that support energy and calm.",
      "Mark completion daily to maintain momentum.",
      "Protect one recovery habit even on busy days.",
    ],
  },
  {
    id: "finance-tracking",
    title: "Finance Tracking",
    points: [
      "Record income, expenses, and savings regularly.",
      "Review categories weekly to spot patterns.",
      "Use small corrections early to avoid bigger stress later.",
    ],
  },
  {
    id: "dashboard-understanding",
    title: "Dashboard Understanding",
    points: [
      "Use the dashboard for a quick health check across all pillars.",
      "Watch task completion, goal progress, and habit consistency.",
      "Take one action from insights instead of just reading data.",
    ],
  },
  {
    id: "success-guidelines",
    title: "Success Guidelines",
    points: [
      "Keep plans realistic and measurable.",
      "Review often and improve gradually.",
      "Consistency beats intensity over time.",
    ],
  },
];

// Generated by GitHub Copilot
export const USER_GUIDE_TIPS: string[] = [
  "Plan only 3 important tasks each morning.",
  "Link at least one daily task to an active goal.",
  "Use weekly review scores to adjust next week early.",
  "If a goal feels stuck, reduce task size to 20 minutes.",
  "Track one finance metric every day for clarity.",
  "Protect one peace habit before checking evening screens.",
  "Consistency for 5 days is better than intensity for 1 day.",
  "Celebrate completed tasks to reinforce momentum.",
  "Use monthly review to decide what to stop, not just what to add.",
  "When overwhelmed, do the smallest next step now.",
];
