// Generated by GitHub Copilot
import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";
import { DailyTaskCategory } from "@/types";

const TASK_SUGGESTION_MODELS = [
  "gemini-3-flash-preview",
  "gemini-2.5-flash",
  "gemini-1.5-flash",
];

/**
 * Tries configured Gemini models in priority order until one succeeds.
 */
// Generated by GitHub Copilot
async function generateTaskSuggestions(
  ai: GoogleGenAI,
  prompt: string,
): Promise<string | null> {
  for (const model of TASK_SUGGESTION_MODELS) {
    try {
      const response = await ai.models.generateContent({
        model,
        contents: prompt,
        config: {
          temperature: 0.5,
          topP: 0.8,
          maxOutputTokens: 450,
        },
      });

      const text = response.text?.trim();
      if (text) {
        return text;
      }
    } catch (modelError) {
      const message =
        modelError instanceof Error ? modelError.message : String(modelError);
      const isNotFound =
        message.includes("NOT_FOUND") ||
        message.includes("not found") ||
        message.includes("404");

      if (!isNotFound) {
        throw modelError;
      }
    }
  }

  return null;
}

interface SuggestionGoalInput {
  goalId?: string;
  title: string;
  category: DailyTaskCategory;
  subCategory?: string | null;
}

interface SuggestionGroup {
  goalTitle: string;
  goalId?: string;
  suggestions: string[];
}

/**
 * Builds deterministic fallback suggestions by category.
 */
// Generated by GitHub Copilot
function buildFallbackSuggestions(goals: SuggestionGoalInput[], difficultyHint: "easier" | "balanced" | "advanced"): SuggestionGroup[] {
  const byCategory: Record<DailyTaskCategory, string[]> = {
    career: ["Deep work 25 mins", "Review priority task", "Skill practice 20 mins"],
    family: ["Family check-in", "Plan one quality activity", "Support kids routine"],
    finance: ["Review expenses", "Track one saving action", "Check budget category"],
    peace: ["10-min breathing", "Short walk", "Journal for 10 mins"],
  };

  const easingMap: Record<string, string> = {
    easier: "10 mins",
    advanced: "30 mins",
  };

  return goals.slice(0, 5).map((goal) => {
    const base = byCategory[goal.category] ?? ["Progress one small step", "Review this goal", "Plan next action"];
    const adjusted = base.slice(0, 3).map((item) => {
      if (difficultyHint === "balanced") {
        return item;
      }
      return item.replace(/\b(20 mins|25 mins|30 mins|10 mins)\b/, easingMap[difficultyHint]);
    });

    return {
      goalTitle: goal.title,
      goalId: goal.goalId,
      suggestions: adjusted,
    };
  });
}

/**
 * POST /api/task-suggestions
 *
 * Generates up to 3 small daily task suggestions per goal.
 */
export async function POST(request: NextRequest) {
  try {
    const payload = await request.json();
    const goals = (payload?.goals ?? []) as SuggestionGoalInput[];
    const recentTasks = (payload?.recentTasks ?? []) as string[];
    const difficultyHint = (payload?.difficultyHint ?? "balanced") as "easier" | "balanced" | "advanced";

    if (!Array.isArray(goals) || goals.length === 0) {
      return NextResponse.json([], { status: 200 });
    }

    const normalizedGoals = goals
      .filter((goal) => typeof goal?.title === "string" && goal.title.trim().length > 0)
      .slice(0, 5)
      .map((goal) => ({
        goalId: goal.goalId,
        title: goal.title.trim(),
        category: goal.category,
        subCategory: goal.subCategory ?? null,
      }));

    const apiKey = process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      return NextResponse.json(buildFallbackSuggestions(normalizedGoals, difficultyHint));
    }

    const goalsJson = JSON.stringify(normalizedGoals);
    const recentTasksJson = JSON.stringify(recentTasks.slice(0, 12));

    const prompt = `You are an assistant for a Life Balance planner app.

Based on these goals, suggest 3 small daily tasks per goal.
Keep tasks simple, practical, and achievable within 30 minutes.

Goals:\n${goalsJson}
Recent tasks (avoid duplicates where possible):\n${recentTasksJson}
Difficulty hint: ${difficultyHint}

Rules:
1) Return max 3 suggestions per goal.
2) Use clear action verbs.
3) Keep each suggestion under 8 words.
4) Keep suggestions aligned to goal category/subCategory.
5) Do not return markdown.

Return only JSON array with this shape:
[
  {
    "goalTitle": "...",
    "goalId": "...",
    "suggestions": ["...", "...", "..."]
  }
]`;

    const ai = new GoogleGenAI({ apiKey });
    const textContent = await generateTaskSuggestions(ai, prompt);

    if (!textContent || typeof textContent !== "string") {
      return NextResponse.json(buildFallbackSuggestions(normalizedGoals, difficultyHint));
    }

    const jsonMatch = textContent.match(/\[[\s\S]*\]/);
    if (!jsonMatch) {
      return NextResponse.json(buildFallbackSuggestions(normalizedGoals, difficultyHint));
    }

    const parsed = JSON.parse(jsonMatch[0]) as SuggestionGroup[];
    const safe = parsed.slice(0, 5).map((group) => ({
      goalTitle: String(group.goalTitle ?? "").trim(),
      goalId: group.goalId,
      suggestions: Array.isArray(group.suggestions)
        ? group.suggestions.map((item) => String(item).trim()).filter(Boolean).slice(0, 3)
        : [],
    }));

    return NextResponse.json(safe);
  } catch (error) {
    console.error("Task suggestions API error:", error);
    return NextResponse.json([], { status: 200 });
  }
}
