// Generated by GitHub Copilot
import { createSlice, PayloadAction } from "@reduxjs/toolkit";
import { MonthlyReview } from "@/types";

interface MonthlyReviewState {
  reviews: MonthlyReview[];
}

const initialState: MonthlyReviewState = {
  reviews: [],
};

const monthlyReviewSlice = createSlice({
  name: "monthlyReviews",
  initialState,
  reducers: {
    setMonthlyReviews: (state, action: PayloadAction<MonthlyReview[]>) => {
      state.reviews = action.payload;
    },
    addMonthlyReview: (state, action: PayloadAction<MonthlyReview>) => {
      state.reviews.unshift(action.payload);
    },
    replaceMonthlyReview: (state, action: PayloadAction<MonthlyReview>) => {
      state.reviews = state.reviews.map((item) =>
        item.id === action.payload.id ? action.payload : item,
      );
    },
    removeMonthlyReview: (state, action: PayloadAction<string>) => {
      state.reviews = state.reviews.filter((item) => item.id !== action.payload);
    },
  },
});

export const {
  setMonthlyReviews,
  addMonthlyReview,
  replaceMonthlyReview,
  removeMonthlyReview,
} = monthlyReviewSlice.actions;

export default monthlyReviewSlice.reducer;
