// Generated by GitHub Copilot
import { GoogleGenAI } from "@google/genai";
import { NextRequest, NextResponse } from "next/server";

const WEEKLY_COACH_MODELS = [
  "gemini-3-flash-preview",
  "gemini-2.5-flash",
  "gemini-1.5-flash",
];

/**
 * Tries configured Gemini models in priority order until one succeeds.
 */
// Generated by GitHub Copilot
async function generateWeeklySuggestion(
  ai: GoogleGenAI,
  prompt: string,
): Promise<string | null> {
  for (const model of WEEKLY_COACH_MODELS) {
    try {
      const response = await ai.models.generateContent({
        model,
        contents: prompt,
        config: {
          temperature: 0.7,
          topP: 0.8,
          maxOutputTokens: 150,
        },
      });

      const text = response.text?.trim();
      if (text) {
        return text;
      }
    } catch (modelError) {
      const message =
        modelError instanceof Error ? modelError.message : String(modelError);
      const isNotFound =
        message.includes("NOT_FOUND") ||
        message.includes("not found") ||
        message.includes("404");

      if (!isNotFound) {
        throw modelError;
      }
    }
  }

  return null;
}

/**
 * POST /api/weekly-coach
 * 
 * Generates AI-powered improvement suggestions based on weekly tasks and pillar scores.
 * Calls Google Gemini API to provide actionable guidance.
 * 
 * Request body:
 * {
 *   completedTasks: string[],
 *   pendingTasks: string[],
 *   scores: { career, family, finance, peace },
 *   completionRate: number
 * }
 */
export async function POST(request: NextRequest) {
  try {
    const payload = await request.json();
    const { completedTasks, pendingTasks, scores, completionRate } = payload;

    // Validate input
    if (!Array.isArray(completedTasks) || !Array.isArray(pendingTasks)) {
      return NextResponse.json({ error: "Invalid task arrays" }, { status: 400 });
    }

    if (!scores || typeof scores.career !== "number") {
      return NextResponse.json({ error: "Invalid scores" }, { status: 400 });
    }

    // Get API key from environment
    const apiKey = process.env.GEMINI_API_KEY ?? process.env.GOOGLE_API_KEY;
    if (!apiKey) {
      console.warn("GEMINI_API_KEY not configured, using fallback suggestion");
      return NextResponse.json({
        suggestion:
          "Focus on completing pending tasks next week. Build consistency in your lowest-scoring pillar.",
      });
    }

    // Find the weakest pillar
    const pillars = [
      { name: "career", score: scores.career },
      { name: "family", score: scores.family },
      { name: "finance", score: scores.finance },
      { name: "peace", score: scores.peace },
    ];
    const weakestPillar = pillars.reduce((min, p) => (p.score < min.score ? p : min));

    // Build the prompt
    const completedList = completedTasks.length > 0 ? completedTasks.join("\n• ") : "None";
    const pendingList = pendingTasks.length > 0 ? pendingTasks.join("\n• ") : "None";

    const prompt = `You are a life coaching AI assistant. Based on the weekly tasks and pillar scores below, provide ONE SHORT and ACTIONABLE improvement suggestion for next week.

**Completed Tasks (${completedTasks.length}):**
• ${completedList}

**Pending Tasks (${pendingTasks.length}):**
• ${pendingList}

**Pillar Scores:**
• Career: ${scores.career}/10
• Family: ${scores.family}/10
• Finance: ${scores.finance}/10
• Peace: ${scores.peace}/10
• Completion Rate: ${completionRate}%

**Weakest Area:** ${weakestPillar.name} (${weakestPillar.score}/10)

Requirements:
1. Keep response under 3 sentences (40-80 words max)
2. Be practical and immediately actionable
3. Use an encouraging, supportive tone
4. Focus on ${weakestPillar.name} if possible, or the highest-impact improvement
5. Reference the pending tasks or completion rate if relevant`;

    const ai = new GoogleGenAI({ apiKey });
    const suggestion = await generateWeeklySuggestion(ai, prompt);

    if (!suggestion) {
      return NextResponse.json({
        suggestion: `This week, focus on completing pending tasks and strengthening your ${weakestPillar.name} pillar. Start with one high-impact task.`,
      });
    }

    return NextResponse.json({ suggestion });
  } catch (error) {
    console.error("Weekly coach API error:", error);

    // Return graceful fallback
    return NextResponse.json({
      suggestion:
        "You've made good progress. Next week, prioritize your pending tasks and build momentum from today's wins.",
    });
  }
}
