"use client";

import { useEffect, useMemo, useState } from "react";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import AddRoundedIcon from "@mui/icons-material/AddRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import {
  Box,
  Button,
  Card,
  CardContent,
  Checkbox,
  Chip,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  IconButton,
  List,
  ListItem,
  ListItemSecondaryAction,
  ListItemText,
  MenuItem,
  FormControlLabel,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import { formatTimeHms } from "@/lib/date-time";
import { getWeekOfMonth } from "@/lib/goal-utils";
import { DailyTask, DailyTaskCategory, Goal, WeekTag } from "@/types";

interface DailyChecklistProps {
  title: string;
  tasks: DailyTask[];
  goals?: Goal[];
  prefillDraft?: { title: string; category: DailyTaskCategory; goalId?: string | null } | null;
  onPrefillConsumed?: () => void;
  listMaxHeight?: number | string;
  onToggle: (id: string) => void;
  onDelete: (id: string) => void;
  onAdd: (title: string, category: DailyTaskCategory, options?: { recurring?: boolean; goalId?: string | null; subCategory?: string | null; weekTag?: WeekTag | null; taskDate?: string | null }) => void;
  onEdit: (id: string, title: string, category: DailyTaskCategory, options?: { goalId?: string | null; subCategory?: string | null; weekTag?: WeekTag | null; taskDate?: string | null }) => void;
}

const categories: DailyTaskCategory[] = [
  "career", "family", "finance", "peace",
];

const WEEK_TAG_OPTIONS: Array<{ value: WeekTag; label: string }> = [
  { value: "week1", label: "Week 1 (Language)" },
  { value: "week2", label: "Week 2 (Discipline)" },
  { value: "week3", label: "Week 3 (Physical)" },
  { value: "week4", label: "Week 4 (Values)" },
];

// Generated by GitHub Copilot
function getSubCategoryOptions(category: DailyTaskCategory): string[] {
  switch (category) {
    case "family":
      return ["kids", "general"];
    case "peace":
      return ["health", "personal", "general"];
    default:
      return ["general"];
  }
}

/**
 * Provides a checklist view for daily tasks with add, toggle, and delete actions.
 */
export default function DailyChecklist({
  title,
  tasks,
  goals = [],
  prefillDraft,
  onPrefillConsumed,
  listMaxHeight,
  onToggle,
  onDelete,
  onAdd,
  onEdit,
}: DailyChecklistProps) {
  const today = new Date().toISOString().slice(0, 10);
  const [open, setOpen] = useState(false);
  const [draftTitle, setDraftTitle] = useState("");
  const [draftCategory, setDraftCategory] = useState<DailyTaskCategory>("career");
  const [draftSubCategory, setDraftSubCategory] = useState<string | null>(null);
  const [draftTaskDate, setDraftTaskDate] = useState(today);
  const [draftWeekTag, setDraftWeekTag] = useState<WeekTag | null>(null);
  const [draftGoalId, setDraftGoalId] = useState<string | null>(null);
  const [draftRecurring, setDraftRecurring] = useState(false);
  const [editingTask, setEditingTask] = useState<DailyTask | null>(null);
  const [editTitle, setEditTitle] = useState("");
  const [editCategory, setEditCategory] = useState<DailyTaskCategory>("career");
  const [editSubCategory, setEditSubCategory] = useState<string | null>(null);
  const [editTaskDate, setEditTaskDate] = useState(today);
  const [editWeekTag, setEditWeekTag] = useState<WeekTag | null>(null);
  const [editGoalId, setEditGoalId] = useState<string | null>(null);

  const isDraftKidsTask = draftCategory === "family" && draftSubCategory === "kids";
  const isEditKidsTask = editCategory === "family" && editSubCategory === "kids";

  useEffect(() => {
    if (open && isDraftKidsTask && !draftWeekTag) {
      setDraftWeekTag(getWeekOfMonth(new Date()));
    }
  }, [draftWeekTag, isDraftKidsTask, open]);

  useEffect(() => {
    if (!isDraftKidsTask && draftWeekTag) {
      setDraftWeekTag(null);
    }
  }, [draftWeekTag, isDraftKidsTask]);

  useEffect(() => {
    if (editingTask && isEditKidsTask && !editWeekTag) {
      setEditWeekTag(getWeekOfMonth(new Date()));
    }
  }, [editWeekTag, editingTask, isEditKidsTask]);

  useEffect(() => {
    if (!isEditKidsTask && editWeekTag) {
      setEditWeekTag(null);
    }
  }, [editWeekTag, isEditKidsTask]);

  useEffect(() => {
    if (!prefillDraft) {
      return;
    }

    setDraftTitle(prefillDraft.title);
    setDraftCategory(prefillDraft.category);
    setDraftSubCategory(null);
    setDraftTaskDate(today);
    setDraftWeekTag(null);
    setDraftGoalId(prefillDraft.goalId ?? null);
    setDraftRecurring(false);
    setOpen(true);
    onPrefillConsumed?.();
  }, [onPrefillConsumed, prefillDraft, today]);

  // Generated by GitHub Copilot
  const activeLinkableGoals = useMemo(
    () => goals.filter((goal) => !goal.completed && (goal.goalType ?? "task") !== "master"),
    [goals],
  );

  // Generated by GitHub Copilot
  const filteredDraftGoals = useMemo(
    () => activeLinkableGoals.filter((goal) => goal.category === draftCategory),
    [activeLinkableGoals, draftCategory],
  );

  // Generated by GitHub Copilot
  const filteredEditGoals = useMemo(
    () => activeLinkableGoals.filter((goal) => goal.category === editCategory),
    [activeLinkableGoals, editCategory],
  );

  // Generated by GitHub Copilot
  const goalMap = useMemo(
    () => Object.fromEntries(goals.map((goal) => [goal.id, goal.title])),
    [goals],
  );

  /**
   * Applies category and auto-suggests a milestone goal in that category.
   */
  function handleDraftCategoryChange(category: DailyTaskCategory) {
    setDraftCategory(category);
    setDraftSubCategory(null);
    setDraftWeekTag(null);
    const categoryGoals = activeLinkableGoals.filter((goal) => goal.category === category);
    const defaultGoal = categoryGoals.find((goal) => (goal.goalType ?? "task") === "milestone");
    setDraftGoalId(defaultGoal?.id ?? null);
  }

  /**
   * Applies edit category and auto-suggests a milestone goal in that category.
   */
  function handleEditCategoryChange(category: DailyTaskCategory) {
    setEditCategory(category);
    setEditSubCategory(null);
    setEditWeekTag(null);
    const categoryGoals = activeLinkableGoals.filter((goal) => goal.category === category);
    const defaultGoal = categoryGoals.find((goal) => (goal.goalType ?? "task") === "milestone");
    setEditGoalId(defaultGoal?.id ?? null);
  }

  /**
   * Submits a new task only when a title is provided.
   */
  function handleSubmit() {
    if (!draftTitle.trim()) {
      return;
    }

    onAdd(draftTitle.trim(), draftCategory, {
      recurring: draftRecurring,
      goalId: draftGoalId,
      subCategory: draftSubCategory,
      taskDate: draftTaskDate || today,
      weekTag: isDraftKidsTask ? (draftWeekTag ?? getWeekOfMonth(new Date())) : null,
    });
    setDraftTitle("");
    setDraftCategory("career");
    setDraftSubCategory(null);
    setDraftTaskDate(today);
    setDraftWeekTag(null);
    setDraftGoalId(null);
    setDraftRecurring(false);
    setOpen(false);
  }

  /**
   * Opens the edit dialog and pre-fills the selected task values.
   */
  function openEdit(task: DailyTask) {
    setEditingTask(task);
    setEditTitle(task.title);
    setEditCategory(task.category);
    setEditSubCategory(task.subCategory ?? null);
    setEditTaskDate(task.taskDate ?? task.createdAt.slice(0, 10));
    setEditWeekTag(task.weekTag ?? null);
    const categoryGoals = activeLinkableGoals.filter((goal) => goal.category === task.category);
    const existingGoal = task.goalId ? categoryGoals.find((goal) => goal.id === task.goalId) : undefined;
    const defaultGoal = categoryGoals.find((goal) => (goal.goalType ?? "task") === "milestone");
    setEditGoalId(existingGoal?.id ?? defaultGoal?.id ?? null);
  }

  /**
   * Persists edits when a non-empty title is provided.
   */
  function handleSaveEdit() {
    if (!editingTask || !editTitle.trim()) {
      return;
    }

    onEdit(editingTask.id, editTitle.trim(), editCategory, {
      goalId: editGoalId,
      subCategory: editSubCategory,
      taskDate: editTaskDate || today,
      weekTag: isEditKidsTask ? (editWeekTag ?? getWeekOfMonth(new Date())) : null,
    });
    setEditingTask(null);
  }

  return (
    <>
      <Card sx={{ height: "100%" }}>
        <CardContent>
          <Stack direction="row" justifyContent="space-between" alignItems="center" mb={2}>
            <div>
              <Typography variant="h5">{title}</Typography>
              <Typography variant="body2" color="text.secondary">
                Keep the day finite and visible.
              </Typography>
            </div>
            <Button
              startIcon={<AddRoundedIcon />}
              variant="contained"
              onClick={() => {
                setDraftTaskDate(today);
                setOpen(true);
              }}
            >
              Add Task
            </Button>
          </Stack>
          <Box
            sx={{
              maxHeight: listMaxHeight,
              overflowY: listMaxHeight ? "auto" : "visible",
              pr: listMaxHeight ? 0.5 : 0,
              "&::-webkit-scrollbar": {
                width: "6px",
              },
              "&::-webkit-scrollbar-track": {
                background: "transparent",
              },
              "&::-webkit-scrollbar-thumb": {
                background: "rgba(0, 0, 0, 0.2)",
                borderRadius: "3px",
                "&:hover": {
                  background: "rgba(0, 0, 0, 0.3)",
                },
              },
            }}
          >
            <List disablePadding>
              {tasks.map((task) => (
                <ListItem key={task.id} divider sx={{ pr: 7 }}>
                  <Checkbox
                    edge="start"
                    checked={task.completed}
                    onChange={() => onToggle(task.id)}
                    inputProps={{ "aria-label": `Toggle task ${task.title}` }}
                  />
                  <ListItemText
                    primary={task.title}
                    secondaryTypographyProps={{ component: "div" }}
                    secondary={
                      <Stack spacing={0.5}>
                        <Stack direction="row" spacing={1} alignItems="center" useFlexGap flexWrap="wrap">
                          <Typography variant="body2" color="text.secondary">
                            {`${task.category}${task.subCategory ? ` • ${task.subCategory}` : ""} • ${task.taskDate ?? task.createdAt.slice(0, 10)} • ${formatTimeHms(task.createdAt)}`}
                          </Typography>
                          {task.subCategory === "kids" && task.weekTag ? (
                            <Chip size="small" variant="outlined" label={getWeekTagLabel(task.weekTag)} />
                          ) : null}
                        </Stack>
                        {task.goalId && goalMap[task.goalId] ? (
                          <Chip
                            size="small"
                            variant="outlined"
                            label={`Goal: ${goalMap[task.goalId]}`}
                            sx={{ width: "fit-content" }}
                          />
                        ) : null}
                      </Stack>
                    }
                    primaryTypographyProps={{
                      sx: {
                        textDecoration: task.completed ? "line-through" : "none",
                      },
                    }}
                  />
                  <ListItemSecondaryAction>
                    <IconButton
                      edge="end"
                      aria-label={`Edit task ${task.title}`}
                      onClick={() => openEdit(task)}
                    >
                      <EditRoundedIcon />
                    </IconButton>
                    <IconButton
                      edge="end"
                      aria-label={`Delete task ${task.title}`}
                      onClick={() => onDelete(task.id)}
                    >
                      <DeleteOutlineRoundedIcon />
                    </IconButton>
                  </ListItemSecondaryAction>
                </ListItem>
              ))}
            </List>
          </Box>
          {tasks.length === 0 ? (
            <Typography variant="body2" color="text.secondary" sx={{ mt: 2 }}>
              No tasks yet. Add the few actions that actually move today forward.
            </Typography>
          ) : null}
        </CardContent>
      </Card>
      <Dialog open={open} onClose={() => setOpen(false)} fullWidth maxWidth="sm">
        <DialogTitle>Add Daily Task</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ pt: 1 }}>
            <TextField
              label="Task title"
              value={draftTitle}
              onChange={(event) => setDraftTitle(event.target.value)}
              fullWidth
            />
            <TextField
              type="date"
              label="Date"
              value={draftTaskDate}
              onChange={(event) => setDraftTaskDate(event.target.value || today)}
              InputLabelProps={{ shrink: true }}
              fullWidth
            />
            <TextField
              select
              label="Category"
              value={draftCategory}
              onChange={(event) => handleDraftCategoryChange(event.target.value as DailyTaskCategory)}
              fullWidth
            >
              {categories.map((category) => (
                <MenuItem key={category} value={category}>
                  {category}
                </MenuItem>
              ))}
            </TextField>
            {(draftCategory === "family" || draftCategory === "peace") ? (
              <TextField
                select
                label="Sub-category (optional)"
                value={draftSubCategory ?? ""}
                onChange={(event) => setDraftSubCategory(event.target.value || null)}
                fullWidth
              >
                <MenuItem value="">None</MenuItem>
                {getSubCategoryOptions(draftCategory).map((subCategory) => (
                  <MenuItem key={subCategory} value={subCategory}>
                    {subCategory}
                  </MenuItem>
                ))}
              </TextField>
            ) : null}
            {isDraftKidsTask ? (
              <TextField
                select
                label="Week (Kids Focus)"
                value={draftWeekTag ?? ""}
                onChange={(event) => setDraftWeekTag((event.target.value || null) as WeekTag | null)}
                fullWidth
              >
                <MenuItem value="">Auto (current week)</MenuItem>
                {WEEK_TAG_OPTIONS.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            ) : null}
            <TextField
              select
              label="Goal (optional)"
              value={draftGoalId ?? ""}
              onChange={(event) => setDraftGoalId(event.target.value || null)}
              fullWidth
            >
              <MenuItem value="">None</MenuItem>
              {filteredDraftGoals.map((goal) => (
                <MenuItem key={goal.id} value={goal.id}>
                  {goal.title}
                </MenuItem>
              ))}
            </TextField>
            <FormControlLabel
              control={<Checkbox checked={draftRecurring} onChange={(event) => setDraftRecurring(event.target.checked)} />}
              label="Repeat daily"
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpen(false)}>Cancel</Button>
          <Button variant="contained" onClick={handleSubmit}>
            Save
          </Button>
        </DialogActions>
      </Dialog>
      <Dialog open={Boolean(editingTask)} onClose={() => setEditingTask(null)} fullWidth maxWidth="sm">
        <DialogTitle>Edit Daily Task</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ pt: 1 }}>
            <TextField
              label="Task title"
              value={editTitle}
              onChange={(event) => setEditTitle(event.target.value)}
              fullWidth
            />
            <TextField
              type="date"
              label="Date"
              value={editTaskDate}
              onChange={(event) => setEditTaskDate(event.target.value || today)}
              InputLabelProps={{ shrink: true }}
              fullWidth
            />
            <TextField
              select
              label="Category"
              value={editCategory}
              onChange={(event) => handleEditCategoryChange(event.target.value as DailyTaskCategory)}
              fullWidth
            >
              {categories.map((category) => (
                <MenuItem key={category} value={category}>
                  {category}
                </MenuItem>
              ))}
            </TextField>
            {(editCategory === "family" || editCategory === "peace") ? (
              <TextField
                select
                label="Sub-category (optional)"
                value={editSubCategory ?? ""}
                onChange={(event) => setEditSubCategory(event.target.value || null)}
                fullWidth
              >
                <MenuItem value="">None</MenuItem>
                {getSubCategoryOptions(editCategory).map((subCategory) => (
                  <MenuItem key={subCategory} value={subCategory}>
                    {subCategory}
                  </MenuItem>
                ))}
              </TextField>
            ) : null}
            {isEditKidsTask ? (
              <TextField
                select
                label="Week (Kids Focus)"
                value={editWeekTag ?? ""}
                onChange={(event) => setEditWeekTag((event.target.value || null) as WeekTag | null)}
                fullWidth
              >
                <MenuItem value="">Auto (current week)</MenuItem>
                {WEEK_TAG_OPTIONS.map((option) => (
                  <MenuItem key={option.value} value={option.value}>
                    {option.label}
                  </MenuItem>
                ))}
              </TextField>
            ) : null}
            <TextField
              select
              label="Goal (optional)"
              value={editGoalId ?? ""}
              onChange={(event) => setEditGoalId(event.target.value || null)}
              fullWidth
            >
              <MenuItem value="">None</MenuItem>
              {filteredEditGoals.map((goal) => (
                <MenuItem key={goal.id} value={goal.id}>
                  {goal.title}
                </MenuItem>
              ))}
            </TextField>
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditingTask(null)}>Cancel</Button>
          <Button variant="contained" onClick={handleSaveEdit}>Save</Button>
        </DialogActions>
      </Dialog>
    </>
  );
}

function getWeekTagLabel(weekTag: WeekTag): string {
  switch (weekTag) {
    case "week1":
      return "Week 1 (Language)";
    case "week2":
      return "Week 2 (Discipline)";
    case "week3":
      return "Week 3 (Physical)";
    case "week4":
      return "Week 4 (Values)";
    default:
      return weekTag;
  }
}