// Generated by GitHub Copilot
"use client";

import EmojiEventsRoundedIcon from "@mui/icons-material/EmojiEventsRounded";
import TrendingUpRoundedIcon from "@mui/icons-material/TrendingUpRounded";
import {
  Box,
  Button,
  Card,
  CardContent,
  Chip,
  LinearProgress,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";
import { Goal, WeeklyReview, moduleColors } from "@/types";
import { getLevelProgress, getLevelUpSuggestion } from "@/lib/goal-utils";

interface MasterGoalCardProps {
  goal: Goal;
  reviews: WeeklyReview[];
  /** Called when the user confirms a level-up action. */
  onPromoteLevel: (goal: Goal) => void;
}

/**
 * Renders the master goal card with level progress, pillar score, and level-up CTA.
 *
 * Accessibility: all interactive elements use visible focus rings and aria labels.
 */
export default function MasterGoalCard({
  goal,
  reviews,
  onPromoteLevel,
}: MasterGoalCardProps) {
  const progressPercent = getLevelProgress(goal);
  const { canLevelUp, message } = getLevelUpSuggestion(goal, reviews);
  const accent = moduleColors[goal.category] ?? "#1E88E5";

  // Compute latest pillar score from most recent review
  const latestReview = reviews[0];
  const pillarScoreMap: Record<string, number> = {
    career: latestReview?.careerScore ?? 0,
    family: latestReview?.familyScore ?? 0,
    finance: latestReview?.financeScore ?? 0,
    peace: latestReview?.peaceScore ?? 0,
  };
  const weeklyScore = pillarScoreMap[goal.category] ?? 0;

  return (
    <Card
      sx={{
        height: "100%",
        background: `linear-gradient(160deg, #ffffff 60%, ${accent}14 100%)`,
        border: `1px solid ${accent}28`,
        position: "relative",
        overflow: "hidden",
      }}
    >
      <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
        <Stack spacing={2}>
          {/* Header */}
          <Stack direction="row" spacing={1} alignItems="flex-start">
            <Box sx={{ flex: 1 }}>
              <Chip
                label="Master Goal"
                size="small"
                sx={{
                  mb: 0.75,
                  bgcolor: `${accent}20`,
                  color: accent,
                  fontWeight: 700,
                  fontSize: "0.7rem",
                }}
              />
              <Typography variant="h6" sx={{ fontWeight: 700, lineHeight: 1.25 }}>
                {goal.title}
              </Typography>
              {goal.description ? (
                <Typography variant="body2" color="text.secondary" sx={{ mt: 0.4, lineHeight: 1.5 }}>
                  {goal.description}
                </Typography>
              ) : null}
            </Box>
            <EmojiEventsRoundedIcon sx={{ color: accent, opacity: 0.55, fontSize: 28, mt: 0.25 }} />
          </Stack>

          {/* Level info */}
          <Stack spacing={0.75}>
            <Stack direction="row" justifyContent="space-between" alignItems="center">
              <Typography variant="body2" sx={{ fontWeight: 700, color: "text.primary" }}>
                Level {goal.levelCurrent ?? 1} → {goal.levelTarget ?? 5}
              </Typography>
              <Typography variant="caption" sx={{ color: accent, fontWeight: 700 }}>
                {progressPercent}%
              </Typography>
            </Stack>
            <LinearProgress
              variant="determinate"
              value={progressPercent}
              sx={{
                height: 8,
                borderRadius: 999,
                bgcolor: `${accent}22`,
                "& .MuiLinearProgress-bar": { bgcolor: accent, borderRadius: 999 },
              }}
              aria-label={`Level progress: ${progressPercent} percent`}
            />
          </Stack>

          {/* Weekly score for the pillar */}
          <Stack direction="row" spacing={1} alignItems="center">
            <TrendingUpRoundedIcon sx={{ color: accent, fontSize: 18 }} />
            <Typography variant="body2" color="text.secondary">
              This week&apos;s {goal.category} score:
            </Typography>
            <Typography variant="body2" sx={{ fontWeight: 700, color: accent }}>
              {weeklyScore}/10
            </Typography>
          </Stack>

          {/* Level-up suggestion or status */}
          <Typography variant="caption" color="text.secondary" sx={{ lineHeight: 1.5 }}>
            {message}
          </Typography>

          {/* Promote Level button */}
          {canLevelUp && (goal.levelCurrent ?? 1) < (goal.levelTarget ?? 5) ? (
            <Tooltip title="Confirm level-up — all recent review scores meet the threshold.">
              <Button
                variant="contained"
                size="small"
                onClick={() => onPromoteLevel(goal)}
                sx={{
                  alignSelf: "flex-start",
                  bgcolor: accent,
                  "&:hover": { bgcolor: accent, filter: "brightness(0.92)" },
                  fontWeight: 700,
                }}
                aria-label={`Promote ${goal.title} to level ${(goal.levelCurrent ?? 1) + 1}`}
              >
                Promote to Level {(goal.levelCurrent ?? 1) + 1}
              </Button>
            </Tooltip>
          ) : null}
        </Stack>
      </CardContent>

      {/* Decorative accent circle */}
      <Box
        aria-hidden
        sx={{
          position: "absolute",
          right: -24,
          bottom: -24,
          width: 96,
          height: 96,
          borderRadius: "50%",
          bgcolor: `${accent}12`,
        }}
      />
    </Card>
  );
}
