// Generated by GitHub Copilot
"use client";

import FavoriteRoundedIcon from "@mui/icons-material/FavoriteRounded";
import { Card, CardContent, Stack, Typography } from "@mui/material";

const TIP =
  "\"Let us plan together\" — small acts of shared ownership build trust that lasts far beyond any single conversation.";

const AVOID =
  "Avoid: \"You don't understand\" — replace it with \"Help me understand your perspective.\"";

/**
 * Renders a static relationship reminder card for the dashboard.
 * Promotes calm, constructive communication language.
 *
 * Accessibility: card uses a semantic landmark and descriptive text.
 */
export default function RelationshipReminderCard() {
  return (
    <Card
      component="aside"
      aria-label="Relationship communication tip"
      sx={{
        height: "100%",
        background: "linear-gradient(160deg, #fff8f0 0%, #fff3e0 100%)",
        border: "1px solid rgba(251,140,0,0.18)",
      }}
    >
      <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
        <Stack spacing={1.75}>
          <Stack direction="row" spacing={1} alignItems="center">
            <FavoriteRoundedIcon sx={{ color: "#FB8C00", fontSize: 20 }} />
            <Typography
              variant="overline"
              sx={{ color: "#FB8C00", fontWeight: 800, letterSpacing: "0.08em" }}
            >
              Relationship Tip
            </Typography>
          </Stack>
          <Typography variant="body1" sx={{ fontWeight: 700, lineHeight: 1.5 }}>
            {TIP}
          </Typography>
          <Typography variant="body2" color="text.secondary" sx={{ lineHeight: 1.55 }}>
            {AVOID}
          </Typography>
        </Stack>
      </CardContent>
    </Card>
  );
}
