"use client";

import { useState } from "react";
import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  IconButton,
  Stack,
  Tooltip,
  Typography,
} from "@mui/material";
import HelpOutlineRoundedIcon from "@mui/icons-material/HelpOutlineRounded";
import { MODULE_QUICK_GUIDE } from "@/constants/moduleQuickGuide";

interface ModuleQuickGuideProps {
  pathname: string;
}

/**
 * Shows concise route-level help to reduce form confusion and improve productivity.
 */
// Generated by GitHub Copilot
export default function ModuleQuickGuide({ pathname }: ModuleQuickGuideProps) {
  const [open, setOpen] = useState(false);
  const content = MODULE_QUICK_GUIDE[pathname];

  if (!content) {
    return null;
  }

  return (
    <>
      <Tooltip title="Open quick help guide" arrow>
        <IconButton
          color="inherit"
          size="small"
          onClick={() => setOpen(true)}
          aria-label="Open quick guide"
          sx={{
            width: { xs: 26, md: 30 },
            height: { xs: 26, md: 30 },
            color: "primary.main",
            border: "1px solid rgba(30, 136, 229, 0.45)",
            bgcolor: "rgba(30, 136, 229, 0.05)",
            flexShrink: 0,
            "&:hover": {
              bgcolor: "rgba(30, 136, 229, 0.12)",
              borderColor: "rgba(30, 136, 229, 0.7)",
            },
          }}
        >
          <HelpOutlineRoundedIcon fontSize="small" />
        </IconButton>
      </Tooltip>

      <Dialog
        open={open}
        onClose={() => setOpen(false)}
        fullWidth
        maxWidth="sm"
        aria-labelledby="quick-guide-dialog-title"
        PaperProps={{
          sx: {
            borderRadius: { xs: 1.5, md: 2 },
          },
        }}
      >
        <DialogTitle id="quick-guide-dialog-title">Quick Guide</DialogTitle>
        <DialogContent dividers>
          <Stack spacing={1.5}>
            <Stack spacing={0.4}>
              <Typography variant="caption" sx={{ fontWeight: 700 }}>
                Module focus
              </Typography>
              <Typography variant="body2" color="text.secondary">
                {content.focus}
              </Typography>
            </Stack>

            <Stack spacing={0.6}>
              <Typography variant="caption" sx={{ fontWeight: 700 }}>
                What you need to input
              </Typography>
              {content.inputs.map((item) => (
                <Typography key={item} variant="body2" color="text.secondary">
                  - {item}
                </Typography>
              ))}
            </Stack>

            <Stack spacing={0.6}>
              <Typography variant="caption" sx={{ fontWeight: 700 }}>
                What output you get
              </Typography>
              {content.outputs.map((item) => (
                <Typography key={item} variant="body2" color="text.secondary">
                  - {item}
                </Typography>
              ))}
            </Stack>
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setOpen(false)} variant="contained">
            Close
          </Button>
        </DialogActions>
      </Dialog>
    </>
  );
}
