"use client";

import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useMemo, useState } from "react";
import { useDispatch, useSelector } from "react-redux";
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  Checkbox,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  FormControlLabel,
  Grid,
  IconButton,
  LinearProgress,
  MenuItem,
  Stack,
  TextField,
  Tooltip,
  Typography,
} from "@mui/material";
import PageHeader from "@/components/common/PageHeader";
import StatCard from "@/components/common/StatCard";
import DailyChecklist from "@/components/dashboard/DailyChecklist";
import LifeRadarChart from "@/components/dashboard/LifeRadarChart";
import LifeScoreCard from "@/components/dashboard/LifeScoreCard";
import MasterGoalCard from "@/components/dashboard/MasterGoalCard";
import RelationshipReminderCard from "@/components/dashboard/RelationshipReminderCard";
import { useAuth } from "@/lib/auth-context";
import { getGoalLevelSnapshot } from "@/lib/goal-level";
import { getRecurringMilestoneGoals } from "@/lib/goal-templates";
import {
  createDailyTask,
  deleteDailyTask,
  promoteGoalLevel,
  updateDailyTask,
  updateDailyTaskCompletion,
} from "@/lib/persistence";
import { getLatestWeeklyReview } from "@/lib/score";
import {
  getFamilySubCategoryBreakdown,
  getPeaceSubCategoryBreakdown,
  getWeekOfMonth,
} from "@/lib/goal-utils";
import { STORAGE_KEYS } from "@/constants/storage";
import { USER_GUIDE_TIPS } from "@/constants/userGuide";
import { addTask, removeTask, replaceTask } from "@/store/slices/dailySlice";
import { replaceGoal } from "@/store/slices/goalsSlice";
import { AppDispatch, RootState } from "@/store/store";
import {
  DailyTaskCategory,
  Goal,
  moduleColors,
  PillarSummary,
  WeekTag,
} from "@/types";

function toDateOnly(value: string) {
  return value.slice(0, 10);
}

interface CardHelpTooltipProps {
  label: string;
  text: string;
}

/**
 * Shows compact purpose guidance for each dashboard card.
 */
// Generated by GitHub Copilot
function CardHelpTooltip({ label, text }: CardHelpTooltipProps) {
  return (
    <Tooltip title={text} arrow enterTouchDelay={0}>
      <IconButton
        size="small"
        aria-label={`About ${label}`}
        sx={{ color: "text.secondary", ml: 0.25 }}
      >
        <Box
          component="span"
          sx={{
            width: 16,
            height: 16,
            borderRadius: "50%",
            border: "1px solid",
            borderColor: "currentColor",
            display: "inline-flex",
            alignItems: "center",
            justifyContent: "center",
            fontSize: "0.7rem",
            fontWeight: 700,
            lineHeight: 1,
          }}
        >
          i
        </Box>
      </IconButton>
    </Tooltip>
  );
}

/**
 * Renders the main dashboard with scorecards, charts, tasks, and quick actions.
 */
export default function DashboardPage() {
  const router = useRouter();
  const dispatch = useDispatch<AppDispatch>();
  const { user, isHydrating } = useAuth();
  const [error, setError] = useState<string | null>(null);
  const [plannerView, setPlannerView] = useState<"today" | "all">("today");
  const [taskSortBy, setTaskSortBy] = useState<
    "category-asc" | "category-desc"
  >("category-asc");
  const [selectedGoalId, setSelectedGoalId] = useState<string | null>(null);
  const [showGuideIntro, setShowGuideIntro] = useState(false);
  const [hideGuidePreference, setHideGuidePreference] = useState(false);
  const tasks = useSelector((state: RootState) => state.daily.tasks);
  const reviews = useSelector(
    (state: RootState) => state.weeklyReviews.reviews,
  );
  const goals = useSelector((state: RootState) => state.goals.goals);
  const habits = useSelector((state: RootState) => state.habits.habits);
  const latestReview = getLatestWeeklyReview(reviews);

  const pillars: PillarSummary[] = [
    {
      key: "career",
      title: "Career",
      description: "Execution, learning, and momentum in meaningful work.",
      score: latestReview?.careerScore ?? 0,
      color: moduleColors.career,
    },
    {
      key: "family",
      title: "Family",
      description: "Presence, reliability, and emotional availability at home.",
      score: latestReview?.familyScore ?? 0,
      color: moduleColors.family,
    },
    {
      key: "finance",
      title: "Finance",
      description: "Clarity on cash flow, savings, and strategic investments.",
      score: latestReview?.financeScore ?? 0,
      color: moduleColors.finance,
    },
    {
      key: "peace",
      title: "Peace",
      description: "Energy, calm, boundaries, and recovery across the week.",
      score: latestReview?.peaceScore ?? 0,
      color: moduleColors.peace,
    },
  ];

  const completedTasks = tasks.filter((task) => task.completed).length;
  const completionRate = tasks.length
    ? Math.round((completedTasks / tasks.length) * 100)
    : 0;
  const completedGoals = goals.filter((goal) => goal.completed).length;
  const completedHabits = habits.filter((habit) => habit.completedToday).length;

  // Generated by GitHub Copilot
  const recurringMilestoneGoals = useMemo(
    () => getRecurringMilestoneGoals(goals),
    [goals],
  );
  const recurringMilestoneGoalIds = useMemo(
    () => new Set(recurringMilestoneGoals.map((goal) => goal.id)),
    [recurringMilestoneGoals],
  );
  const linkedRecurringGoalTasks = useMemo(
    () =>
      tasks.filter(
        (task) => task.goalId && recurringMilestoneGoalIds.has(task.goalId),
      ),
    [recurringMilestoneGoalIds, tasks],
  );
  const completedLinkedRecurringGoalTasks = linkedRecurringGoalTasks.filter(
    (task) => task.completed,
  ).length;

  // Generated by GitHub Copilot - Calculate sub-category breakdowns
  const familyBreakdown = getFamilySubCategoryBreakdown(tasks);
  const peaceBreakdown = getPeaceSubCategoryBreakdown(tasks);
  const scoreNote = `${completedTasks}/${Math.max(tasks.length, 1)} tasks complete, ${goals.filter((goal) => goal.completed).length} goals closed, ${habits.filter((habit) => habit.completedToday).length} habits done today.`;

  // Generated by GitHub Copilot - Monthly completion selector by task planned date fallback
  const monthPrefix = new Date().toISOString().slice(0, 7);
  const monthlyTasks = useMemo(
    () =>
      tasks.filter((task) =>
        (task.taskDate ?? toDateOnly(task.createdAt)).startsWith(monthPrefix),
      ),
    [tasks, monthPrefix],
  );

  const monthlyCompletionByCategory = useMemo(() => {
    const categories: DailyTaskCategory[] = [
      "career",
      "family",
      "finance",
      "peace",
    ];
    const result = categories.map((category) => {
      const categoryTasks = monthlyTasks.filter(
        (task) => task.category === category,
      );
      const total = categoryTasks.length;
      const completed = categoryTasks.filter((task) => task.completed).length;
      const percent = total > 0 ? Math.round((completed / total) * 100) : 0;
      return { category, total, completed, percent };
    });

    return result;
  }, [monthlyTasks]);

  // Generated by GitHub Copilot
  const topGoalsProgress = useMemo(() => {
    return goals
      .filter((goal) => (goal.goalType ?? "task") !== "master")
      .map((goal) => {
        const snapshot = getGoalLevelSnapshot(goal, tasks, reviews);
        return {
          id: goal.id,
          title: goal.title,
          levelCurrent: goal.levelCurrent ?? 1,
          levelTarget: goal.levelTarget ?? 5,
          completedTasks: snapshot.completedTasks,
          progressToNextPercent: snapshot.progressToNextPercent,
          nextLevel: snapshot.nextLevel,
          nextLevelThreshold: snapshot.nextLevelThreshold,
        };
      })
      .sort((a, b) => {
        if (b.completedTasks !== a.completedTasks) {
          return b.completedTasks - a.completedTasks;
        }
        return b.progressToNextPercent - a.progressToNextPercent;
      })
      .slice(0, 4);
  }, [goals, reviews, tasks]);

  // Generated by GitHub Copilot
  const tipOfTheDay = useMemo(() => {
    const now = new Date();
    const dayOfYear = Math.floor(
      (Date.UTC(now.getFullYear(), now.getMonth(), now.getDate()) -
        Date.UTC(now.getFullYear(), 0, 0)) /
        86400000,
    );
    return USER_GUIDE_TIPS[dayOfYear % USER_GUIDE_TIPS.length];
  }, []);

  // Generated by GitHub Copilot
  useEffect(() => {
    if (typeof window === "undefined" || !user?.id) {
      return;
    }
    const hidden =
      window.localStorage.getItem(STORAGE_KEYS.hideGuide) === "true";
    const seen =
      window.localStorage.getItem(
        `${STORAGE_KEYS.guideIntroSeen}:${user.id}`,
      ) === "true";
    if (!hidden && !seen) {
      setShowGuideIntro(true);
    }
  }, [user?.id]);

  // Generated by GitHub Copilot
  function handleSkipGuideIntro() {
    if (typeof window !== "undefined" && user?.id) {
      window.localStorage.setItem(
        `${STORAGE_KEYS.guideIntroSeen}:${user.id}`,
        "true",
      );
      if (hideGuidePreference) {
        window.localStorage.setItem(STORAGE_KEYS.hideGuide, "true");
      }
    }
    setShowGuideIntro(false);
  }

  // Generated by GitHub Copilot
  function handleViewGuide() {
    if (typeof window !== "undefined" && user?.id) {
      window.localStorage.setItem(
        `${STORAGE_KEYS.guideIntroSeen}:${user.id}`,
        "true",
      );
      if (hideGuidePreference) {
        window.localStorage.setItem(STORAGE_KEYS.hideGuide, "true");
      }
    }
    setShowGuideIntro(false);
    router.push("/user-guide");
  }

  const plannerTasks = useMemo(
    () =>
      plannerView === "today"
        ? tasks.filter(
            (task) =>
              toDateOnly(task.taskDate ?? task.createdAt) ===
              toDateOnly(new Date().toISOString()),
          )
        : tasks,
    [plannerView, tasks],
  );

  const filteredTasks = useMemo(
    () =>
      selectedGoalId
        ? plannerTasks.filter((task) => task.goalId === selectedGoalId)
        : plannerTasks,
    [plannerTasks, selectedGoalId],
  );

  // Generated by GitHub Copilot - Sort tasks by category
  const sortedTasks = useMemo(() => {
    const sorted = [...filteredTasks].sort((a, b) => {
      const comparison = a.category.localeCompare(b.category);
      return taskSortBy === "category-asc" ? comparison : -comparison;
    });
    return sorted;
  }, [filteredTasks, taskSortBy]);

  // Shifts all card sections 4 px left without affecting the page header.
  const cardShiftSx = { ml: "-4px", mr: "-4px" };

  // Master-type goals visible on the dashboard
  const masterGoals = goals.filter((goal) => goal.goalType === "master");

  /**
   * Promotes a goal's level and syncs Redux state.
   */
  async function handlePromoteLevel(goal: Goal) {
    try {
      setError(null);
      const updatedGoal = await promoteGoalLevel(goal);
      dispatch(replaceGoal(updatedGoal));
    } catch (promotionError) {
      setError(
        promotionError instanceof Error
          ? promotionError.message
          : "Failed to promote goal level.",
      );
    }
  }

  /**
   * Creates a daily task and persists it in Supabase.
   */
  async function handleAddTask(
    title: string,
    category: DailyTaskCategory,
    options?: {
      recurring?: boolean;
      goalId?: string | null;
      subCategory?: string | null;
      weekTag?: WeekTag | null;
      taskDate?: string | null;
    },
  ) {
    if (!user) {
      return;
    }

    try {
      setError(null);
      const isKidsTask =
        category === "family" && options?.subCategory === "kids";
      const resolvedWeekTag = isKidsTask
        ? (options?.weekTag ?? getWeekOfMonth(new Date()))
        : null;
      const task = await createDailyTask(user.id, {
        title,
        category,
        subCategory: options?.subCategory ?? null,
        weekTag: resolvedWeekTag,
        taskDate: options?.taskDate ?? new Date().toISOString().slice(0, 10),
      });
      dispatch(addTask(task));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to add task.",
      );
    }
  }

  /**
   * Toggles a task and persists the completion state.
   */
  async function handleToggleTask(id: string) {
    const task = tasks.find((item) => item.id === id);
    if (!task) {
      return;
    }

    try {
      setError(null);
      const updatedTask = await updateDailyTaskCompletion(id, !task.completed);
      dispatch(replaceTask(updatedTask));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to update task.",
      );
    }
  }

  /**
   * Deletes a task from Supabase and Redux state.
   */
  async function handleDeleteTask(id: string) {
    try {
      setError(null);
      await deleteDailyTask(id);
      dispatch(removeTask(id));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to delete task.",
      );
    }
  }

  /**
   * Completes all incomplete tasks in the current view.
   */
  async function handleCompleteAll() {
    try {
      setError(null);
      const incompleteTasks = sortedTasks.filter((task) => !task.completed);
      for (const task of incompleteTasks) {
        const updatedTask = await updateDailyTaskCompletion(task.id, true);
        dispatch(replaceTask(updatedTask));
      }
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to complete all tasks.",
      );
    }
  }

  /**
   * Updates task title/category and syncs Redux state.
   */
  async function handleEditTask(
    id: string,
    title: string,
    category: DailyTaskCategory,
    options?: {
      goalId?: string | null;
      subCategory?: string | null;
      weekTag?: WeekTag | null;
      taskDate?: string | null;
    },
  ) {
    try {
      setError(null);
      const isKidsTask =
        category === "family" && options?.subCategory === "kids";
      const resolvedWeekTag = isKidsTask
        ? (options?.weekTag ?? getWeekOfMonth(new Date()))
        : null;
      const updatedTask = await updateDailyTask(id, {
        title,
        category,
        subCategory: options?.subCategory ?? null,
        weekTag: resolvedWeekTag,
        taskDate: options?.taskDate ?? null,
      });
      dispatch(replaceTask(updatedTask));
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to update task.",
      );
    }
  }

  return (
    <Stack spacing={3}>
      <PageHeader
        eyebrow="Weekly Operating View"
        title="Balance the week before it drifts"
        description="LifeBalanceOS keeps the four pillars, today’s commitments, and your recovery signals in one calm command surface."
      >
        <Stack direction={{ xs: "column", sm: "row" }} spacing={1.5}>
          <Button component={Link} href="/weekly-review" variant="contained">
            Review This Week
          </Button>
          <Button component={Link} href="/daily" variant="outlined">
            Open Planner
          </Button>
        </Stack>
      </PageHeader>
      {error ? <Alert severity="error">{error}</Alert> : null}
      <Box sx={cardShiftSx}>
        <Grid container spacing={{ xs: 2, md: 3 }}>
          <Grid item xs={12} md={6} xl={3}>
            <Tooltip title="Your overall balance score based on the latest weekly review and daily execution." arrow>
              <Box>
                <LifeScoreCard
                  score={latestReview?.lifeBalanceScore ?? 0}
                  note={scoreNote}
                />
              </Box>
            </Tooltip>
          </Grid>
          <Grid item xs={12} md={6} xl={3}>
            <Tooltip title="Shows how much of your current checklist has been completed." arrow>
              <Box>
                <StatCard
                  label="Task Completion"
                  value={`${completionRate}%`}
                  support={`${completedTasks} of ${tasks.length} daily tasks completed.`}
                  accent={moduleColors.career}
                />
              </Box>
            </Tooltip>
          </Grid>
          <Grid item xs={12} md={6} xl={3}>
            <Tooltip title="Tracks the number of goals completed across all modules." arrow>
              <Box>
                <StatCard
                  label="Goals Closed"
                  value={`${completedGoals}`}
                  support={`${goals.length - completedGoals} still in active focus.`}
                  accent={moduleColors.finance}
                />
              </Box>
            </Tooltip>
          </Grid>
          <Grid item xs={12} md={6} xl={3}>
            <Tooltip title="Daily habit completion snapshot to help keep consistency visible." arrow>
              <Box>
                <StatCard
                  label="Habits Today"
                  value={`${completedHabits}`}
                  support={`${habits.length - completedHabits} habits still open today.`}
                  accent={moduleColors.peace}
                />
              </Box>
            </Tooltip>
          </Grid>
        </Grid>
      </Box>
      <Box sx={cardShiftSx}>
        <Grid container spacing={{ xs: 2, md: 3 }}>
          <Grid item xs={12}>
            <Tooltip title="Radar view compares your four pillar scores from the latest weekly review." arrow>
              <Box>
                <LifeRadarChart pillars={pillars} isHydrating={isHydrating} />
              </Box>
            </Tooltip>
          </Grid>
        </Grid>
      </Box>
      <Box sx={cardShiftSx}>
        <Grid container spacing={3}>
          <Grid item xs={12} lg={8}>
            <Card>
              <CardContent sx={{ pb: 2 }}>
                <Stack
                  direction={{ xs: "column", sm: "row" }}
                  spacing={{ xs: 1.5, sm: 2 }}
                  alignItems={{ xs: "flex-start", sm: "center" }}
                  justifyContent="space-between"
                  sx={{ mb: "5px" }}
                >
                  <Stack spacing={0.5}>
                    <Stack direction="row" spacing={0.5} alignItems="center" sx={{ flexWrap: "wrap" }}>
                      <Typography variant="h6" gutterBottom={false}>
                        Today&apos;s Checklist
                      </Typography>
                      <CardHelpTooltip
                        label="Today's Checklist"
                        text="Your execution list for today or all tasks, with quick filtering, sorting, and bulk completion."
                      />
                    </Stack>
                    <Typography variant="caption" color="text.secondary">
                      Total: {sortedTasks.length} / Completed:{" "}
                      {sortedTasks.filter((t) => t.completed).length}
                    </Typography>
                  </Stack>
                  <Stack
                    direction="row"
                    spacing={1.25}
                    useFlexGap
                    flexWrap="wrap"
                    sx={{ width: { xs: "100%", md: "auto" } }}
                  >
                    <Button
                      variant="outlined"
                      size="small"
                      onClick={handleCompleteAll}
                      disabled={
                        sortedTasks.length === 0 ||
                        sortedTasks.every((t) => t.completed)
                      }
                      sx={{ minWidth: { xs: "100%", sm: 140 } }}
                    >
                      Complete All
                    </Button>
                    <TextField
                      select
                      size="small"
                      label="View"
                      value={plannerView}
                      onChange={(e) =>
                        setPlannerView(e.target.value as "today" | "all")
                      }
                      sx={{ minWidth: { xs: "100%", sm: 120 } }}
                    >
                      <MenuItem value="today">Today</MenuItem>
                      <MenuItem value="all">All Tasks</MenuItem>
                    </TextField>
                    <TextField
                      select
                      size="small"
                      label="Goal"
                      value={selectedGoalId ?? ""}
                      onChange={(e) =>
                        setSelectedGoalId(e.target.value || null)
                      }
                      sx={{ minWidth: { xs: "100%", sm: 180 } }}
                    >
                      <MenuItem value="">All Tasks</MenuItem>
                      {goals.map((goal) => (
                        <MenuItem key={goal.id} value={goal.id}>
                          {goal.title}
                        </MenuItem>
                      ))}
                    </TextField>
                    <TextField
                      select
                      size="small"
                      label="Sort by"
                      value={taskSortBy}
                      onChange={(e) =>
                        setTaskSortBy(
                          e.target.value as "category-asc" | "category-desc",
                        )
                      }
                      sx={{ minWidth: { xs: "100%", sm: 160 } }}
                    >
                      <MenuItem value="category-asc">Category (A-Z)</MenuItem>
                      <MenuItem value="category-desc">Category (Z-A)</MenuItem>
                    </TextField>
                  </Stack>
                </Stack>
              </CardContent>

              <DailyChecklist
                title=""
                tasks={sortedTasks}
                goals={goals}
                listMaxHeight={520}
                onToggle={handleToggleTask}
                onDelete={handleDeleteTask}
                onAdd={handleAddTask}
                onEdit={handleEditTask}
              />
            </Card>
          </Grid>
          <Grid item xs={12} lg={4}>
            <Stack
              direction={{ xs: "column", lg: "row" }}
              spacing={2}
              alignItems="stretch"
              sx={{ height: { xs: "auto", lg: "100%" } }}
            >
              <Card sx={{ flex: 1, minWidth: 0 }}>
                <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
                  <Tooltip title="Shows the most recent weekly review checkpoint so you always know your latest baseline." arrow>
                    <Box>
                      <StatCard
                        label="Quick Insight"
                        value={
                          latestReview ? `${latestReview.weekStart}` : "No review"
                        }
                        support={
                          latestReview
                            ? "Latest weekly review anchor date."
                            : "Create your first weekly review to generate a balance score."
                        }
                        accent={moduleColors.family}
                      />
                    </Box>
                  </Tooltip>
                </CardContent>
              </Card>
              <Card sx={{ flex: 1, minWidth: 0 }}>
                <CardContent
                  sx={{
                    p: { xs: 2.5, md: 3 },
                    height: { xs: "auto", lg: "100%" },
                    display: "flex",
                    flexDirection: "column",
                  }}
                >
                  <Stack direction="row" spacing={0.5} alignItems="center" sx={{ mb: 1.5 }}>
                    <Typography variant="h6" sx={{ fontWeight: 700 }}>
                      Quick Actions
                    </Typography>
                    <CardHelpTooltip
                      label="Quick Actions"
                      text="Shortcuts to your most-used modules so you can move through your planning flow faster."
                    />
                  </Stack>
                  <Stack spacing={1.25} sx={{ flex: { xs: "unset", lg: 1 } }}>
                    <Button
                      component={Link}
                      href="/daily"
                      variant="contained"
                      fullWidth
                      sx={{ minHeight: 44 }}
                    >
                      Daily Planner
                    </Button>
                    <Button
                      component={Link}
                      href="/weekly-review"
                      variant="outlined"
                      fullWidth
                      sx={{ minHeight: 44 }}
                    >
                      Weekly Review
                    </Button>
                    <Button
                      component={Link}
                      href="/monthly-review"
                      variant="outlined"
                      fullWidth
                      sx={{ minHeight: 44 }}
                    >
                      Monthly Review
                    </Button>
                    <Button
                      component={Link}
                      href="/finance"
                      variant="outlined"
                      fullWidth
                      sx={{ minHeight: 44 }}
                    >
                      Finance
                    </Button>
                    <Button
                      component={Link}
                      href="/reflections"
                      variant="outlined"
                      fullWidth
                      sx={{ minHeight: 44 }}
                    >
                      Reflection
                    </Button>
                  </Stack>
                </CardContent>
              </Card>
            </Stack>
          </Grid>
        </Grid>
      </Box>
      <Box sx={cardShiftSx}>
        <Card>
          <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
            <Stack spacing={1}>
              <Stack direction="row" spacing={0.5} alignItems="center">
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Tip of the Day
                </Typography>
                <CardHelpTooltip
                  label="Tip of the Day"
                  text="A daily coaching nudge to keep your planning and execution aligned."
                />
              </Stack>
              <Typography color="text.secondary">{tipOfTheDay}</Typography>
              <Button
                component={Link}
                href="/user-guide"
                variant="text"
                sx={{ alignSelf: "flex-start", px: 0 }}
              >
                Open Full User Guide
              </Button>
            </Stack>
          </CardContent>
        </Card>
      </Box>
      <Box sx={cardShiftSx}>
        <Card>
          <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
            <Stack spacing={0.5} sx={{ mb: { xs: 2, md: 2.5 } }}>
              <Stack direction="row" spacing={0.5} alignItems="center" sx={{ flexWrap: "wrap" }}>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Pillar Performance
                </Typography>
                <CardHelpTooltip
                  label="Pillar Performance"
                  text="One view that combines pillar score and monthly execution for each life area."
                />
              </Stack>
              <Stack direction={{ xs: "column", sm: "row" }} spacing={{ xs: 0.25, sm: 2 }} alignItems={{ xs: "flex-start", sm: "center" }} flexWrap="wrap">
                <Typography variant="body2" color="text.secondary">
                  {monthPrefix}
                </Typography>
                <Typography variant="body2" color="text.secondary" sx={{ display: "flex", alignItems: "center", gap: 0.5 }}>
                  <Box component="span" sx={{ fontWeight: 600, color: "primary.main" }}>{completedLinkedRecurringGoalTasks}</Box>
                  {" / "}
                  {linkedRecurringGoalTasks.length} goal-linked tasks completed
                </Typography>
              </Stack>
            </Stack>
            <Grid container spacing={2} alignItems="stretch">
              {pillars.map((pillar) => {
                const monthly = monthlyCompletionByCategory.find((item) => item.category === pillar.key);
                const monthlyPercent = monthly?.percent ?? 0;
                const monthlyCompleted = monthly?.completed ?? 0;
                const monthlyTotal = monthly?.total ?? 0;

                return (
                  <Grid item xs={12} sm={6} md={6} lg={3} key={pillar.key}>
                    <Stack
                      spacing={1.1}
                      sx={{
                        p: { xs: 1.75, sm: 2.25 },
                        bgcolor: "action.hover",
                        borderRadius: 2,
                        height: "100%",
                        minHeight: { xs: 156, sm: 170 },
                        transition: "box-shadow 0.2s",
                        "&:hover": { boxShadow: 2 },
                      }}
                    >
                      <Stack direction="row" justifyContent="space-between" alignItems="center" spacing={1} sx={{ minHeight: 20 }}>
                        <Typography variant="overline" sx={{ fontWeight: 800, letterSpacing: "0.08em", color: pillar.color, lineHeight: 1.4 }}>
                          {pillar.title}
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          Score {pillar.score}/10
                        </Typography>
                      </Stack>
                      <LinearProgress
                        variant="determinate"
                        value={pillar.score * 10}
                        sx={{
                          height: 7,
                          borderRadius: 999,
                          bgcolor: "divider",
                          "& .MuiLinearProgress-bar": { bgcolor: pillar.color },
                        }}
                      />
                      <Stack direction="row" justifyContent="space-between" alignItems="baseline" sx={{ pt: 0.25 }}>
                        <Typography variant="h5" sx={{ fontWeight: 800, fontSize: { xs: "1.5rem", sm: "1.6rem" }, color: monthlyPercent === 100 ? "success.main" : "primary.main" }}>
                          {monthlyPercent}%
                        </Typography>
                        <Typography variant="caption" color="text.secondary">
                          {monthlyCompleted}/{monthlyTotal} done
                        </Typography>
                      </Stack>
                      <Box>
                        <Box sx={{ height: 5, bgcolor: "divider", borderRadius: 999, overflow: "hidden", mb: 0.5 }}>
                          <Box
                            sx={{
                              height: "100%",
                              width: `${monthlyPercent}%`,
                              bgcolor: monthlyPercent === 100 ? "success.main" : "primary.main",
                              borderRadius: 999,
                              transition: "width 0.4s ease",
                            }}
                          />
                        </Box>
                        <Typography variant="caption" color="text.secondary">
                          Monthly completion
                        </Typography>
                      </Box>
                    </Stack>
                  </Grid>
                );
              })}
            </Grid>
          </CardContent>
        </Card>
      </Box>
      {masterGoals.length > 0 ? (
        <Box sx={cardShiftSx}>
          <Grid container spacing={{ xs: 2, md: 3 }}>
            {masterGoals.map((goal) => (
              <Grid item xs={12} sm={6} xl={3} key={goal.id}>
                <Tooltip title={`Long-horizon priority tracker for ${goal.title}.`} arrow>
                  <Box>
                    <MasterGoalCard
                      goal={goal}
                      reviews={reviews}
                      onPromoteLevel={handlePromoteLevel}
                    />
                  </Box>
                </Tooltip>
              </Grid>
            ))}
          </Grid>
        </Box>
      ) : null}
      {familyBreakdown.length > 0 || peaceBreakdown.length > 0 ? (
        <Box sx={cardShiftSx}>
          <Grid container spacing={{ xs: 2, md: 3 }}>
            {familyBreakdown.length > 0 && (
              <Grid item xs={12} md={6}>
                <Card>
                  <CardContent>
                    <Stack direction="row" spacing={0.5} alignItems="center" sx={{ mb: 2 }}>
                      <Typography variant="h6" sx={{ fontWeight: 700 }}>
                        Family Sub-Categories
                      </Typography>
                      <CardHelpTooltip
                        label="Family Sub-Categories"
                        text="Breaks down family tasks by focus area so you can rebalance attention early."
                      />
                    </Stack>
                    <Stack spacing={1.5}>
                      {familyBreakdown.map((sub) => (
                        <Stack key={sub.name} spacing={0.5}>
                          <Stack direction="row" justifyContent="space-between">
                            <Typography
                              variant="body2"
                              sx={{
                                fontWeight: 600,
                                textTransform: "capitalize",
                              }}
                            >
                              {sub.name}
                            </Typography>
                            <Typography
                              variant="body2"
                              sx={{
                                color:
                                  sub.percentage === 100
                                    ? "success.main"
                                    : "text.secondary",
                              }}
                            >
                              {sub.completed}/{sub.count}
                            </Typography>
                          </Stack>
                          <Box
                            sx={{
                              height: 6,
                              bgcolor: "action.hover",
                              borderRadius: 999,
                              overflow: "hidden",
                            }}
                          >
                            <Box
                              sx={{
                                height: "100%",
                                width: `${sub.percentage}%`,
                                bgcolor:
                                  sub.percentage === 100
                                    ? "success.main"
                                    : moduleColors.family,
                                transition: "width 0.3s ease",
                              }}
                            />
                          </Box>
                        </Stack>
                      ))}
                    </Stack>
                  </CardContent>
                </Card>
              </Grid>
            )}
            {peaceBreakdown.length > 0 && (
              <Grid item xs={12} md={6}>
                <Card>
                  <CardContent>
                    <Stack direction="row" spacing={0.5} alignItems="center" sx={{ mb: 2 }}>
                      <Typography variant="h6" sx={{ fontWeight: 700 }}>
                        Peace Sub-Categories
                      </Typography>
                      <CardHelpTooltip
                        label="Peace Sub-Categories"
                        text="Shows where your wellness and recovery tasks are concentrated this period."
                      />
                    </Stack>
                    <Stack spacing={1.5}>
                      {peaceBreakdown.map((sub) => (
                        <Stack key={sub.name} spacing={0.5}>
                          <Stack direction="row" justifyContent="space-between">
                            <Typography
                              variant="body2"
                              sx={{
                                fontWeight: 600,
                                textTransform: "capitalize",
                              }}
                            >
                              {sub.name}
                            </Typography>
                            <Typography
                              variant="body2"
                              sx={{
                                color:
                                  sub.percentage === 100
                                    ? "success.main"
                                    : "text.secondary",
                              }}
                            >
                              {sub.completed}/{sub.count}
                            </Typography>
                          </Stack>
                          <Box
                            sx={{
                              height: 6,
                              bgcolor: "action.hover",
                              borderRadius: 999,
                              overflow: "hidden",
                            }}
                          >
                            <Box
                              sx={{
                                height: "100%",
                                width: `${sub.percentage}%`,
                                bgcolor:
                                  sub.percentage === 100
                                    ? "success.main"
                                    : moduleColors.peace,
                                transition: "width 0.3s ease",
                              }}
                            />
                          </Box>
                        </Stack>
                      ))}
                    </Stack>
                  </CardContent>
                </Card>
              </Grid>
            )}
          </Grid>
        </Box>
      ) : null}
      <Box sx={cardShiftSx}>
        <Card>
          <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
            <Stack spacing={0.5} sx={{ mb: { xs: 2, md: 2.5 } }}>
              <Stack direction="row" spacing={0.5} alignItems="center" sx={{ flexWrap: "wrap" }}>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Top Goals Progress
                </Typography>
                <CardHelpTooltip
                  label="Top Goals Progress"
                  text="Highlights goals with the strongest execution and level advancement momentum."
                />
              </Stack>
              <Typography variant="body2" color="text.secondary">
                Your most active goals, ranked by completed linked tasks.
              </Typography>
            </Stack>
            {topGoalsProgress.length === 0 ? (
              <Typography variant="body2" color="text.secondary">
                Link daily tasks to goals to track long-term level progress.
              </Typography>
            ) : (
              <Stack spacing={1.5}>
                {topGoalsProgress.map((item) => (
                  <Stack
                    key={item.id}
                    spacing={1}
                    sx={{
                      px: { xs: 1.5, sm: 2 },
                      py: { xs: 1.5, sm: 1.75 },
                      bgcolor: "action.hover",
                      borderRadius: 3,
                      transition: "box-shadow 0.2s",
                      "&:hover": { boxShadow: 2 },
                    }}
                  >
                    <Stack direction={{ xs: "column", sm: "row" }} justifyContent="space-between" alignItems={{ xs: "flex-start", sm: "center" }} spacing={1}>
                      <Typography variant="body2" sx={{ fontWeight: 700, lineHeight: 1.3, flex: 1 }}>
                        {item.title}
                      </Typography>
                      <Box sx={{ px: 1, py: 0.25, bgcolor: "primary.main", borderRadius: 2, flexShrink: 0 }}>
                        <Typography variant="caption" sx={{ color: "primary.contrastText", fontWeight: 700, whiteSpace: "nowrap" }}>
                          L{item.levelCurrent} / {item.levelTarget}
                        </Typography>
                      </Box>
                    </Stack>
                    <LinearProgress
                      variant="determinate"
                      value={item.progressToNextPercent}
                      sx={{ height: 6, borderRadius: 999 }}
                    />
                    <Typography variant="caption" color="text.secondary">
                      {item.nextLevelThreshold
                        ? `${item.completedTasks} / ${item.nextLevelThreshold} tasks to reach Level ${item.nextLevel}`
                        : `${item.completedTasks} linked tasks completed`}
                    </Typography>
                  </Stack>
                ))}
              </Stack>
            )}
          </CardContent>
        </Card>
      </Box>
      <Box sx={cardShiftSx}>
        <Tooltip title="Prompts to maintain relationship consistency through timely, meaningful follow-ups." arrow>
          <Box>
            <RelationshipReminderCard />
          </Box>
        </Tooltip>
      </Box>

      <Dialog
        open={showGuideIntro}
        onClose={handleSkipGuideIntro}
        fullWidth
        maxWidth="xs"
      >
        <DialogTitle>Welcome to Life Balance OS</DialogTitle>
        <DialogContent>
          <Stack spacing={1.5} sx={{ pt: 1 }}>
            <Typography color="text.secondary">
              Start with the User Guide to learn the daily, weekly, and monthly
              rhythm.
            </Typography>
            <FormControlLabel
              control={
                <Checkbox
                  checked={hideGuidePreference}
                  onChange={(event) =>
                    setHideGuidePreference(event.target.checked)
                  }
                />
              }
              label="Do not show again"
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={handleSkipGuideIntro}>Skip</Button>
          <Button variant="contained" onClick={handleViewGuide}>
            View Guide
          </Button>
        </DialogActions>
      </Dialog>
    </Stack>
  );
}

