// Generated by GitHub Copilot
"use client";

import { useEffect, useMemo, useState } from "react";
import DeleteOutlineRoundedIcon from "@mui/icons-material/DeleteOutlineRounded";
import EditRoundedIcon from "@mui/icons-material/EditRounded";
import { useDispatch, useSelector } from "react-redux";
import {
  Alert,
  Box,
  Button,
  Card,
  CardContent,
  CircularProgress,
  Collapse,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Grid,
  IconButton,
  LinearProgress,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import ExpandLessRoundedIcon from "@mui/icons-material/ExpandLessRounded";
import ExpandMoreRoundedIcon from "@mui/icons-material/ExpandMoreRounded";
import PageHeader from "@/components/common/PageHeader";
import { useAuth } from "@/lib/auth-context";
import {
  createMonthlyReview,
  deleteMonthlyReview,
  updateMonthlyReview,
} from "@/lib/persistence";
import {
  currentMonthStart,
  getMonthlyImprovementSuggestion,
} from "@/lib/goal-utils";
import {
  generateMonthlyInsights,
  fetchAIRefinedInsights,
} from "@/lib/useMonthlyInsights";
import {
  addMonthlyReview,
  removeMonthlyReview,
  replaceMonthlyReview,
} from "@/store/slices/monthlyReviewSlice";
import { AppDispatch, RootState } from "@/store/store";

/**
 * Renders the monthly review workflow with improvement tracking and category analysis.
 */
export default function MonthlyReviewPage() {
  const dispatch = useDispatch<AppDispatch>();
  const { user } = useAuth();
  const [error, setError] = useState<string | null>(null);

  const reviews = useSelector(
    (state: RootState) => state.monthlyReviews.reviews,
  );
  const weeklyReviews = useSelector(
    (state: RootState) => state.weeklyReviews.reviews,
  );
  const goals = useSelector((state: RootState) => state.goals.goals);
  const dailyTasks = useSelector((state: RootState) => state.daily.tasks);
  const habits = useSelector((state: RootState) => state.habits.habits);

  const [month, setMonth] = useState(() => currentMonthStart());
  const [improved, setImproved] = useState("");
  const [notImproved, setNotImproved] = useState("");
  const [levelChange, setLevelChange] = useState("");
  const [summaryExpanded, setSummaryExpanded] = useState(true);
  const [historyExpanded, setHistoryExpanded] = useState(true);

  // Insight generation state
  const [isGeneratingInsights, setIsGeneratingInsights] = useState(false);
  const [hasUserEditedImproved, setHasUserEditedImproved] = useState(false);
  const [hasUserEditedNotImproved, setHasUserEditedNotImproved] = useState(false);
  const [hasUserEditedLevelChange, setHasUserEditedLevelChange] = useState(false);
  const [insightError, setInsightError] = useState<string | null>(null);

  const [editingReview, setEditingReview] = useState<
    null | (typeof reviews)[0]
  >(null);
  const [editImproved, setEditImproved] = useState("");
  const [editNotImproved, setEditNotImproved] = useState("");
  const [editLevelChange, setEditLevelChange] = useState("");

  // Monthly summary metrics
  const { lowestCategory, suggestion } = useMemo(
    () => getMonthlyImprovementSuggestion(weeklyReviews),
    [weeklyReviews],
  );

  const completedGoals = goals.filter((g) => g.completed).length;
  const completionPct = goals.length
    ? Math.round((completedGoals / goals.length) * 100)
    : 0;

  /**
   * Auto-generates insights when month or data changes.
   * Does not override if user has manually edited fields.
   */
  useEffect(() => {
    if (
      hasUserEditedImproved ||
      hasUserEditedNotImproved ||
      hasUserEditedLevelChange ||
      !month
    ) {
      return;
    }

    async function autoGenerateInsights() {
      try {
        setIsGeneratingInsights(true);
        setInsightError(null);

        // Generate raw insights
        const rawInsights = generateMonthlyInsights(
          month,
          weeklyReviews,
          dailyTasks,
          goals,
          habits,
          [] // habitLogs - would need to be fetched separately if needed
        );

        // Try to refine with AI (optional)
        const refined = await fetchAIRefinedInsights(rawInsights);

        // Only update if user hasn't edited
        if (!hasUserEditedImproved) setImproved(refined.improved);
        if (!hasUserEditedNotImproved) setNotImproved(refined.notImproved);
        if (!hasUserEditedLevelChange) setLevelChange(refined.levelChange);
      } catch (err) {
        const errMsg = err instanceof Error ? err.message : "Failed to generate insights";
        setInsightError(errMsg);
        console.error("Insight generation error:", err);
      } finally {
        setIsGeneratingInsights(false);
      }
    }

    autoGenerateInsights();
  }, [
    month,
    weeklyReviews,
    dailyTasks,
    goals,
    habits,
    hasUserEditedImproved,
    hasUserEditedNotImproved,
    hasUserEditedLevelChange,
  ]);

  /**
   * Creates and persists a monthly review entry.
   */
  async function handleSave() {
    if (!user || !improved.trim() || !notImproved.trim()) {
      return;
    }

    try {
      setError(null);
      const review = await createMonthlyReview(user.id, {
        month,
        improved: improved.trim(),
        notImproved: notImproved.trim(),
        levelChange: levelChange.trim(),
      });
      dispatch(addMonthlyReview(review));
      setImproved("");
      setNotImproved("");
      setLevelChange("");
      setHasUserEditedImproved(false);
      setHasUserEditedNotImproved(false);
      setHasUserEditedLevelChange(false);
    } catch (submissionError) {
      setError(
        submissionError instanceof Error
          ? submissionError.message
          : "Failed to save monthly review.",
      );
    }
  }

  /**
   * Regenerates insights by resetting user-edit flags and re-triggering generation.
   */
  async function handleRegenerateInsights() {
    setHasUserEditedImproved(false);
    setHasUserEditedNotImproved(false);
    setHasUserEditedLevelChange(false);
    setIsGeneratingInsights(true);

    try {
      setInsightError(null);
      const rawInsights = generateMonthlyInsights(
        month,
        weeklyReviews,
        dailyTasks,
        goals,
        habits,
        []
      );
      const refined = await fetchAIRefinedInsights(rawInsights);
      setImproved(refined.improved);
      setNotImproved(refined.notImproved);
      setLevelChange(refined.levelChange);
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : "Failed to regenerate insights";
      setInsightError(errMsg);
      console.error("Regeneration error:", err);
    } finally {
      setIsGeneratingInsights(false);
    }
  }

  /** Opens edit dialog pre-filled. */
  function openEdit(review: (typeof reviews)[0]) {
    setEditingReview(review);
    setEditImproved(review.improved);
    setEditNotImproved(review.notImproved);
    setEditLevelChange(review.levelChange);
  }

  /** Saves edited review. */
  async function handleSaveEdit() {
    if (!editingReview) return;
    try {
      setError(null);
      const updated = await updateMonthlyReview(editingReview.id, {
        improved: editImproved.trim(),
        notImproved: editNotImproved.trim(),
        levelChange: editLevelChange.trim(),
      });
      dispatch(replaceMonthlyReview(updated));
      setEditingReview(null);
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to update review.");
    }
  }

  /** Deletes a monthly review. */
  async function handleDelete(id: string) {
    try {
      setError(null);
      await deleteMonthlyReview(id);
      dispatch(removeMonthlyReview(id));
    } catch (e) {
      setError(e instanceof Error ? e.message : "Failed to delete review.");
    }
  }

  return (
    <Stack spacing={3} sx={{ py: { xs: 1.5, md: 3 } }}>
      <PageHeader
        title="Monthly Review"
        description="Reflect on what improved, what didn't, and note level changes to guide the next month."
      />
      {error ? <Alert severity="error">{error}</Alert> : null}

      {/* Monthly Summary Card */}
      <Card sx={{ background: "linear-gradient(160deg, #ffffff 60%, #e8f5e914 100%)" }}>
        <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
          <Stack spacing={1.5}>
            <Stack direction="row" alignItems="center" justifyContent="space-between">
              <Typography variant="h6" sx={{ fontWeight: 700 }}>
                Monthly Summary
              </Typography>
              <IconButton
                size="small"
                onClick={() => setSummaryExpanded((prev) => !prev)}
                aria-label={summaryExpanded ? "Collapse summary" : "Expand summary"}
                aria-expanded={summaryExpanded}
              >
                {summaryExpanded ? <ExpandLessRoundedIcon /> : <ExpandMoreRoundedIcon />}
              </IconButton>
            </Stack>
            <Collapse in={summaryExpanded} timeout="auto">
              <Grid container spacing={2}>
                <Grid item xs={12} sm={6}>
                  <Stack spacing={0.75}>
                    <Stack direction="row" justifyContent="space-between">
                      <Typography variant="body2" color="text.secondary">
                        Goal Completion
                      </Typography>
                      <Typography variant="body2" sx={{ fontWeight: 700 }}>
                        {completionPct}% ({completedGoals}/{goals.length})
                      </Typography>
                    </Stack>
                    <LinearProgress
                      variant="determinate"
                      value={completionPct}
                      sx={{ height: 8, borderRadius: 999 }}
                      aria-label={`Goal completion: ${completionPct} percent`}
                    />
                  </Stack>
                </Grid>
                <Grid item xs={12} sm={6}>
                  <Stack spacing={0.5}>
                    <Typography variant="body2" color="text.secondary">
                      Lowest category this month
                    </Typography>
                    <Typography variant="body2" sx={{ fontWeight: 700, color: "error.main" }}>
                      {lowestCategory}
                    </Typography>
                    <Typography variant="caption" color="text.secondary">
                      {suggestion}
                    </Typography>
                  </Stack>
                </Grid>
              </Grid>
            </Collapse>
          </Stack>
        </CardContent>
      </Card>

      {/* Entry Form */}
      <Card>
        <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
          <Stack spacing={2}>
            <Stack direction="row" justifyContent="space-between" alignItems="center">
              <Typography variant="h6" sx={{ fontWeight: 700 }}>
                Add Monthly Review
              </Typography>
              <Button
                size="small"
                variant="outlined"
                onClick={() => void handleRegenerateInsights()}
                disabled={isGeneratingInsights}
              >
                {isGeneratingInsights ? (
                  <>
                    <CircularProgress size={16} sx={{ mr: 1 }} />
                    Generating...
                  </>
                ) : (
                  "🔄 Regenerate"
                )}
              </Button>
            </Stack>

            {isGeneratingInsights && (
              <Alert severity="info" sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
                <CircularProgress size={20} />
                <Typography variant="body2">Analyzing month and generating insights...</Typography>
              </Alert>
            )}

            {insightError && (
              <Alert severity="warning">{insightError}</Alert>
            )}

            <TextField
              type="month"
              label="Month"
              value={month.slice(0, 7)}
              onChange={(e) => {
                setMonth(`${e.target.value}-01`);
                setHasUserEditedImproved(false);
                setHasUserEditedNotImproved(false);
                setHasUserEditedLevelChange(false);
              }}
              InputLabelProps={{ shrink: true }}
              sx={{ maxWidth: 220 }}
            />
            <TextField
              label="What improved this month?"
              value={improved}
              onChange={(e) => {
                setImproved(e.target.value);
                setHasUserEditedImproved(true);
              }}
              placeholder="Auto-filled with AI insights. Edit as needed."
              multiline
              minRows={2}
              fullWidth
              helperText={`${improved.length} characters`}
            />
            <TextField
              label="What didn't improve?"
              value={notImproved}
              onChange={(e) => {
                setNotImproved(e.target.value);
                setHasUserEditedNotImproved(true);
              }}
              placeholder="Auto-filled with AI insights. Edit as needed."
              multiline
              minRows={2}
              fullWidth
              helperText={`${notImproved.length} characters`}
            />
            <TextField
              label="Level change note (optional)"
              value={levelChange}
              onChange={(e) => {
                setLevelChange(e.target.value);
                setHasUserEditedLevelChange(true);
              }}
              placeholder="Auto-filled with AI insights. Edit as needed."
              fullWidth
              helperText={`${levelChange.length} characters`}
            />
            <Button
              variant="contained"
              onClick={() => void handleSave()}
              disabled={!improved.trim() || !notImproved.trim() || isGeneratingInsights}
              sx={{ alignSelf: "flex-start" }}
            >
              Save Review
            </Button>
          </Stack>
        </CardContent>
      </Card>

      {/* Review History */}
      <Card sx={{ height: "fit-content" }}>
        <CardContent sx={{ p: { xs: 2.5, md: 3 } }}>
          <Stack spacing={1.5}>
            <Stack direction="row" alignItems="center" justifyContent="space-between">
              <Stack direction="row" alignItems="center" spacing={1}>
                <Typography variant="h6" sx={{ fontWeight: 700 }}>
                  Review History
                </Typography>
                {!historyExpanded && (
                  <Typography variant="caption" color="text.secondary">
                    {reviews.length} reviews
                  </Typography>
                )}
              </Stack>
              <IconButton
                size="small"
                onClick={() => setHistoryExpanded((prev) => !prev)}
                aria-label={historyExpanded ? "Collapse history" : "Expand history"}
                aria-expanded={historyExpanded}
              >
                {historyExpanded ? <ExpandLessRoundedIcon /> : <ExpandMoreRoundedIcon />}
              </IconButton>
            </Stack>
            <Collapse in={historyExpanded} timeout="auto">
              <Box
                sx={{
                  display: "grid",
                  gap: 2.5,
                  gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
                  maxHeight: 600,
                  overflowY: "auto",
                  pr: 0.5,
                  "&::-webkit-scrollbar": {
                    width: "6px",
                  },
                  "&::-webkit-scrollbar-track": {
                    background: "transparent",
                  },
                  "&::-webkit-scrollbar-thumb": {
                    background: "rgba(0, 0, 0, 0.2)",
                    borderRadius: "3px",
                    "&:hover": {
                      background: "rgba(0, 0, 0, 0.3)",
                    },
                  },
                }}
              >
                {reviews.map((review) => (
                  <Card key={review.id} sx={{ height: "100%" }}>
                    <CardContent>
                      <Stack spacing={1.5}>
                        <Stack direction="row" alignItems="center">
                          <Typography variant="h6" sx={{ flex: 1 }}>
                            {review.month.slice(0, 7)}
                          </Typography>
                          <IconButton
                            size="small"
                            onClick={() => openEdit(review)}
                            aria-label={`Edit review for ${review.month}`}
                          >
                            <EditRoundedIcon fontSize="small" />
                          </IconButton>
                          <IconButton
                            size="small"
                            onClick={() => void handleDelete(review.id)}
                            aria-label={`Delete review for ${review.month}`}
                            sx={{ color: "error.main" }}
                          >
                            <DeleteOutlineRoundedIcon fontSize="small" />
                          </IconButton>
                        </Stack>
                        <Stack spacing={0.5}>
                          <Typography variant="body2" sx={{ fontWeight: 700, color: "success.main" }}>
                            Improved:
                          </Typography>
                          <Typography variant="body2" color="text.secondary">
                            {review.improved}
                          </Typography>
                        </Stack>
                        <Stack spacing={0.5}>
                          <Typography variant="body2" sx={{ fontWeight: 700, color: "error.main" }}>
                            Not improved:
                          </Typography>
                          <Typography variant="body2" color="text.secondary">
                            {review.notImproved}
                          </Typography>
                        </Stack>
                        {review.levelChange ? (
                          <Stack spacing={0.5}>
                            <Typography variant="body2" sx={{ fontWeight: 700 }}>
                              Level change:
                            </Typography>
                            <Typography variant="body2" color="text.secondary">
                              {review.levelChange}
                            </Typography>
                          </Stack>
                        ) : null}
                      </Stack>
                    </CardContent>
                  </Card>
                ))}
              </Box>
            </Collapse>
          </Stack>
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog
        open={Boolean(editingReview)}
        onClose={() => setEditingReview(null)}
        fullWidth
        maxWidth="sm"
      >
        <DialogTitle>Edit Monthly Review</DialogTitle>
        <DialogContent>
          <Stack spacing={2} sx={{ pt: 1 }}>
            <TextField
              label="What improved?"
              value={editImproved}
              onChange={(e) => setEditImproved(e.target.value)}
              multiline
              minRows={2}
              fullWidth
            />
            <TextField
              label="What didn't improve?"
              value={editNotImproved}
              onChange={(e) => setEditNotImproved(e.target.value)}
              multiline
              minRows={2}
              fullWidth
            />
            <TextField
              label="Level change note"
              value={editLevelChange}
              onChange={(e) => setEditLevelChange(e.target.value)}
              fullWidth
            />
          </Stack>
        </DialogContent>
        <DialogActions>
          <Button onClick={() => setEditingReview(null)}>Cancel</Button>
          <Button variant="contained" onClick={() => void handleSaveEdit()}>
            Save
          </Button>
        </DialogActions>
      </Dialog>
    </Stack>
  );
}
